src/main/resources/public/js/admin.js, src/main/resources/public/js/dashboard.js, src/main/resources/public/js/map_utils.js, src/main/resources/template/freemarker/admin.ftl, src/main/resources/template/freemarker/dashboard.ftl
I had to make minor modifications to the map_utils.enable_dragbox_draw function.
=> Angular Modifications to Admin Page

src/main/resources/public/js/dashboard.js, src/main/resources/public/js/map_utils.js, src/main/resources/template/freemarker/dashboard.ftl
1.  getNewPlot() add to Add New Sample plot ng-click event;
2.  needed to modify map_utils.draw_points --> changed looping format from for/in loop to for loop with indexer
3.  needed to modify map_utils.set_current_imagery:
********   This form of looping gave me problems:
for (var layer in layers) {
var title = layers[layer].get("title");
if (title == map_utils.current_imagery && layer < 5) {
layers[layer].set("visible", false);
}
if (title == new_imagery  && layer < 5) {
layers[layer].set("visible", true);
}
}
********   So I replaced it with this:
for (i=0; i<layers.length; i++) {
var layer = layers[i];
var title = layer.get("title");
if (title == map_utils.current_imagery) {
layer.set("visible", false);
}
if (title == new_imagery ) {
layer.set("visible", true);
}
}
=> Dashboard page - enable sample plot display 

pom.xml, src/main/java/org/openforis/ceo/Server.java, src/main/java/org/openforis/ceo/Views.java, src/main/resources/public/js/admin.js, src/main/resources/public/js/dashboard.js
modified:   pom.xml - needed the JSON Simple Dependency to compile
modified:   src/main/java/org/openforis/ceo/Server.java
modified:   src/main/java/org/openforis/ceo/Views.java
modified:   src/main/resources/public/js/admin.js
=> Filled in the Ajax stubs for admin.js

src/main/java/org/openforis/ceo/local/JsonImagery.java, src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/java/org/openforis/ceo/utils/ProjectUtils.java, src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql
This PR contains changes to
Add the new fields (collection start, confidence, and imagery data) to the JSON database
Merge the new fields into the aggregate CSV files on output.
Update the migration script to include new fields.
Update the output of aggregation to only show the new fields if they exist (PG and JSON)
change plotId to integer for both DB
Update PG to work with the new pre/next logic
Add additional Data checks when uploading and migrating data (such as checking if plotId and sampleId are integer)
Allow some variance on the names for the PG csv lon and lat columns.
Add quotes around fields with commas for csv output
=> Many updates to the JSON database

src/main/java/org/openforis/ceo/Server.java, src/main/java/org/openforis/ceo/Views.java, src/main/java/org/openforis/ceo/collect/CollectProjects.java, src/main/java/org/openforis/ceo/db_api/Projects.java, src/main/java/org/openforis/ceo/db_api/Users.java, src/main/java/org/openforis/ceo/local/JsonImagery.java, src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/local/JsonUsers.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresUsers.java, src/main/java/org/openforis/ceo/users/OfUsers.java, src/main/java/org/openforis/ceo/utils/ProjectUtils.java, src/main/resources/public/css/stylesheet.css, src/main/resources/public/jsx/account.js, src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/components/FormLayout.js, src/main/resources/public/jsx/components/SectionBlock.js, src/main/resources/public/jsx/create-project.js, src/main/resources/public/jsx/institution.js, src/main/resources/public/jsx/review-institution.js, src/main/resources/public/jsx/review-project.js, src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/load_ceo_tables.sql, src/main/resources/template/freemarker/account.ftl, src/main/resources/template/freemarker/create-project.ftl, src/main/resources/template/freemarker/review-project.ftl
For user review of plots:
- Update routes to reflect functionality (ie getNextUnanalyzedPlot -> getNextPlot)
- Accept optional query parameter, userName, to filter through user completed plots instead of unanalyzed plots
- Update getPlotById to use the updated plot_id vs plotID logic
- UI add input box and go button for direct selection of plot
- UI checkbox to allow user to go through analyzed plots
- Constraint:  react needs to be updated to handle the incoming data from un-analyzed plots.  This will be a part of another task.
For new survey rules:
- Add new column to the projects table for PG
- Add `survey-rules` as input to API for `createProject`
- Output 'surveyRules` for project JSON data
Relies on PR #166, #167, #168
=> API updates for new survey rules / enhanced user plot navigation

src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/java/org/openforis/ceo/utils/JsonUtils.java, src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql
Add missing commas, and field for migration.
=> Quick fix for PG and migration for new survey_questions

src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/components/SurveyQuestions.js, src/main/resources/public/jsx/create-project.js, src/main/resources/public/jsx/home.js, src/main/resources/public/jsx/review-project.js, src/main/resources/sql/load_ceo_functions.sql
Updates to postgres to allow user to save and overwrite
Fix input box logic to clear on save.  Show color for any answer, inverse for blank
Update message boxes for go to first, prev, next for when user is in review mode
Clear sub question answers on current answer change
Updating some defaults for postgres for edge cases
Fix API submit from UI to include blank value for survey-rules
Style radio button
Misc Formatting
=> Matt avoid dup

src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/components/SurveyDesign.js, src/main/resources/public/jsx/components/SurveyQuestions.js, src/main/resources/public/jsx/create-project.js, src/main/resources/public/jsx/review-project.js
Update survey design to use state instead of DOM access.  Make everything functional
Complete simple / advanced mode
- Prompt user if need to convert advanced to simple
Show more details for survey question (parent question, parent answer, type in advanced mode)
Correctly remove sub questions
Includes updates from comments for #187
=> Update survey design

src/main/resources/public/jsx/components/SurveyDesign.js, src/main/resources/public/jsx/review-project.js
fix = should be ===
space on project status button
remove sloppy matts computer pasting
=> slack fixes

src/main/resources/public/jsx/create-project.js
Making a PR for Matt's fix to the broken Shapefile upload button on the Create Project page.
=> fix htmlFor on file input

src/main/resources/public/jsx/components/SurveyCardList.js, src/main/resources/public/jsx/components/SurveyDesign.js, src/main/resources/public/jsx/review-project.js, src/main/resources/template/freemarker/create-project.ftl, src/main/resources/template/freemarker/review-project.ftl
Group questions into visible survey cards
- Do not use tables so there is a consistent layout
- Visibly show indention to mach question depth
- Show question information: component type, parent question, parent answer
- Allow collapse of entire card
In design mode
- Allow user to move cards up and down
- Style buttons
=> Survey card design

src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/components/SurveyDesign.js, src/main/resources/public/jsx/components/SurveyQuestions.js, src/main/resources/public/jsx/home.js, src/main/resources/public/jsx/review-project.js
* Line 591: Do you want to include [question] in the final result?
* Line 608: This is going to clear the toplevel question as well. Is this intentional?
--- You mentioned this before.  This is needed for the recursion to work as far as I can work it.  It is also OK for the original question to be include, as a new value for that question is being added. (before I filtered it out and you comment on that as well)
* Line 44: Change !every(!==) to every(===).
--- Changed to !some(!==), this will stop check once it finds a non button
* Line 140: Is componentTypes in scope?
--- componentTypes is a global constant
=> fixes for review from 194

README.org, deploy/scripts/cert_renewal.sh, deploy/scripts/packageKeysAndRestartApps.sh, deploy/scripts/startceo.sh, deploy/scripts/startgeegateway.sh
Added scripts to enable https and renew certs.  I also added instructions in the readme.
=> Enable https scripts

src/main/resources/public/jsx/components/SurveyCardList.js, src/main/resources/public/jsx/components/SurveyDesign.js, src/main/resources/public/jsx/components/SurveyQuestions.js, src/main/resources/public/jsx/home.js, src/main/resources/public/jsx/review-project.js
#196 and #197
`<button type="button" >` is required to designate it not a submit.  This may only be and issue here because the create-projects page is a form.
=> Fixes for review from 196

src/main/resources/public/jsx/geo-dash-widget-editor.js
=> fixed dual image asset bug

src/main/java/org/openforis/ceo/Server.java, src/main/resources/public/js/mercator-openlayers.js
=> Added notFound Route

src/main/java/org/openforis/ceo/local/JsonPlots.java, src/main/java/org/openforis/ceo/postgres/PostgresPlots.java, src/main/java/org/openforis/ceo/utils/JsonUtils.java, src/main/resources/public/js/mercator-openlayers.js, src/main/resources/public/jsx/create-project.js
Fix 4 bugs
1. Correctly switch between showing locked template plots and user draw drag box on create projects
2. Add synchronized to several functions
3. Do not update user stats or collection times if user saves over previous sample values (assume that this time for a small correction is << than the original collection time and does not need to be updated).  Do not allow another user to save over previously saved sample values.
4. Fix issues switching between click select and drag select
=> Fix bugs 3-3-2019

src/main/java/org/openforis/ceo/local/JsonGeoDash.java, src/main/java/org/openforis/ceo/local/JsonImagery.java, src/main/java/org/openforis/ceo/local/JsonInstitutions.java, src/main/java/org/openforis/ceo/local/JsonPlots.java, src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/local/JsonUsers.java, src/main/java/org/openforis/ceo/utils/JsonUtils.java
Too many collisions seemed to be the cause of heap out of memory error.
=> Limit file read/write collisions

src/main/resources/public/jsx/geo-dash-widget-editor.js
=> fixed missing basemap imagery

src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/home.js
Edge does not `overflow: "scroll hidden"`.  Changing it to `overflowY: "scroll", overflowX: "hidden"`
=> Use explicit scroll x-y

src/main/resources/scripts/data_migration.py, src/main/resources/scripts/requirements.txt, src/main/resources/shp/shp2postgres.sh, src/main/resources/sql/load_ceo_functions.sql
For the "old" method, use the faster json.load (vs demjson)
For the "new" method pass the json data as a string instead of using /copy inside PG
Script can resume easier.
=> Optimize merge script

build.gradle, deploy/scripts/packageKeysAndRestartApps.sh, deploy/scripts/startgeegateway.sh, pom.xml, src/main/java/org/openforis/ceo/Server.java, src/main/java/org/openforis/ceo/db_api/GeoDash.java, src/main/java/org/openforis/ceo/local/JsonGeoDash.java, src/main/java/org/openforis/ceo/postgres/PostgresGeoDash.java, src/main/resources/public/jsx/geo-dash-widget-editor.js, src/main/resources/public/jsx/geodashreact.js
Enabled a proxy for the gateway to eliminate the client browser from having to use port 8888
=> proxy for gateway

src/main/java/org/openforis/ceo/local/JsonGeoDash.java, src/main/java/org/openforis/ceo/postgres/PostgresGeoDash.java
=> fixed port issue in proxy

src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/load_ceo_tables.sql
Fix tables and migration script
=> migration fixes

src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql
The migration script was not migrating dates
Fix data check for dash
=> migrate dates

deploy/scripts/startceo.sh, src/main/java/org/openforis/ceo/Server.java, src/main/java/org/openforis/ceo/local/JsonImagery.java, src/main/java/org/openforis/ceo/postgres/PostgresImagery.java, src/main/java/org/openforis/ceo/postgres/PostgresInstitutions.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresUsers.java, src/main/resources/public/jsx/account.js, src/main/resources/public/jsx/geo-dash-widget-editor.js, src/main/resources/public/jsx/geodashreact.js, src/main/resources/public/jsx/review-project.js, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/template/freemarker/announcements.ftl
Changes from review
Fix formatting
Create function for adding geodash image for PG.
Finish changes for user functions
=> review changes

deploy/scripts/startceo.sh, src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/resources/public/jsx/home.js, src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/load_ceo_tables.sql, src/main/resources/template/freemarker/announcements.ftl
remove \ in geojson string
validate project boundary on select
=> Fix geometry migration

src/main/resources/public/jsx/review-project.js
Fixed the review project rules issue
=> review project rules

src/main/java/org/openforis/ceo/postgres/PostgresPlots.java, src/main/resources/public/jsx/collection.js, src/main/resources/scripts/data_migration.py, src/main/resources/scripts/redo-shp.py, src/main/resources/sql/load_ceo_functions.sql
Fix the following errors found after migration
1. Archived projects are appearing on the institution page.  
- Add missing filter on query
2. Some projects with shp data did not copy correctly.  
- Project made from templates did not copy enough of the shp data.  Copy template data on migration.  Create update script for already migrated server.
3. Plots do not load correctly in the geodash.
- Use plot_uid instead of plotId, add sample data in Java
4. User stats are negative
- Fix SQL, run update command on server.
5. User can see archived projects by going directly to site
- Show error if trying to load an archived project
=> debug migration

src/main/resources/public/jsx/components/SurveyDesign.js
=> rule id bug fixed

.gitattributes, src/main/resources/csv/csv2postgres-alt.sh, src/main/resources/csv/csv2postgres.sh, src/main/resources/scripts/data_migration.py, src/main/resources/sql/build_db.sh, src/main/resources/sql/load_ceo_functions.sql
Add a couple more try block to handle bad data on prod
=> fixes for prodution migration

src/main/resources/public/js/mercator-openlayers.js, src/main/resources/public/jsx/collection.js
Initial kml download.  It doesn't yet support circle plots but that will be added soon.
=> initial download kml

src/main/resources/public/jsx/collection.js
Included questions for error messages for sum-of-answers, matching-sums.
=> added questions to error messages

src/main/java/org/openforis/ceo/local/JsonProjects.java
This fixes the geodash cloning issue when Copy Template Plots and Samples is unchecked.
=> Githika geodash bug

src/main/resources/public/jsx/geodashreact.js
DigitalGlobe imagery is working again.  remove temporary band-aid
=> revert bandaid

src/main/resources/public/jsx/collection.js
issue #275 
- Allow the user to move on with the survey more quickly by allowing none selected = all visible selected
- Update setCurrentValue to check for selection errors first.
=> none selected = all selected

src/main/resources/public/jsx/home.js, src/main/resources/template/freemarker/announcements.ftl
Add banner to alert users that the bing layer is unavailable
=> Change home page back to digital globe

src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/resources/public/jsx/create-project.js, src/main/resources/sql/build_db.sh, src/main/resources/sql/update_2019_06_02.sql
Update the UI to show the exception messages
=> Check no samples on plots when creating a new project

src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/resources/sql/update_2019_06_02.sql
Expand error message to show the first ten plotIds that have missing samples
=> Show bad plotIds

src/main/java/org/openforis/ceo/Server.java, src/main/java/org/openforis/ceo/Views.java, src/main/resources/public/css/custom.css, src/main/resources/public/jsx/collection.js
Add flash messages on redirect
Block user (would be admin at this point) from saving values to a survey before publishing.
=> More updates from user feadback

src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/java/org/openforis/ceo/utils/ProjectUtils.java, src/main/resources/sql/update_2019_06_13.sql
Add limits for csv and shp files.
Extend to json DB.
=> Update plot limits

src/main/resources/public/jsx/review-institution.js
And dont allow the user to add with duplicate
=> Check for duplicate imagery name before adding

src/main/resources/public/jsx/create-project.js, src/main/resources/public/jsx/home.js, src/main/resources/template/freemarker/home.ftl
Also change default privacy level to institution.
=> Better default filter for homepage institutions

src/main/resources/public/jsx/components/SurveyCardList.js, src/main/resources/public/jsx/components/SurveyDesign.js, src/main/resources/public/jsx/geo-dash.js, src/main/resources/public/jsx/widget-layout-editor.js
=> Mostly linting

webpack.common.js
\n is for linux and \r\n for windows
upgrade nodejs to latest version to avoid errors
=> \n does not work for windows

src/main/resources/sql/archive_config/example_restore_from_server.sh, src/main/resources/sql/archive_config/initiate_restore.sh, src/main/resources/sql/archive_config/recovery.conf, src/main/resources/sql/archive_config/settings.conf, src/main/resources/sql/archive_config/setup_archiving.sh
=> update compression method

package.json, src/main/java/org/openforis/ceo/Proxy.java
This patch sets the GeoServer STYLES param to "default" for each comma-separated entry in the LAYERS param in the event that STYLES has not been specified by the user.
=> Gary fix geoserver proxy

src/main/java/org/openforis/ceo/local/JsonGeoDash.java, src/main/java/org/openforis/ceo/postgres/PostgresGeoDash.java, src/main/java/org/openforis/ceo/postgres/PostgresImagery.java, src/main/resources/public/jsx/widget-layout-editor.js
Addresses issue #350 Update geodashId()
=> Update geodashId() #350

README.org, src/main/resources/scripts/data_migration.py, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/load_ceo_tables.sql
missing comma in load_ceo_tables sql script, wrong function order in load_ceo_functions sql script, updated readme (build_db.sh is no longer available), small change in data_migration.py script
=> just few fixes that solve issues with first time installation

src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/resources/public/jsx/create-project.js, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/load_ceo_tables.sql, src/main/resources/sql/update_2019-12-08.sql
- DB: a "token_key" field has been added into "projects" table
- FRONTEND: the create-project script now CONSUMES a JSON which includes the token key
- BACKEND: the token key is generated at creation time, the create-project endpoint now RETURNS a JSON which includes the token key, the checkAuthCommon method now checks if there is a token in the query string but only if the user isn't logged and allows the access of the collection page only if the token key is valid
=> sepal-ceo integration

src/main/resources/public/js/mercator-openlayers.js, src/main/resources/public/jsx/collection.js
show planet daily option only at plot level
dont make eager call to the gee gateway
=> fix planet daily imagery load

src/main/java/org/openforis/ceo/local/JsonPlots.java, src/main/java/org/openforis/ceo/postgres/PostgresPlots.java, src/main/resources/public/jsx/collection.js, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/update_2020-02-17.sql
with this change is now possible reclassifying a flagged plot
=> closes #395

src/main/resources/public/css/custom.css, src/main/resources/public/js/mercator-openlayers.js, src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/components/ProjectComponents.js, src/main/resources/public/jsx/review-institution.js
=> fix to issue #402

src/main/resources/public/jsx/create-project.js
the descriptions of the structure of the CSV files were incorrect
=> fix to issue #407

src/main/java/org/openforis/ceo/local/JsonUsers.java, src/main/java/org/openforis/ceo/postgres/PostgresUsers.java, src/main/resources/sql/load_ceo_functions.sql
=> send email to user on role add/update

src/main/java/org/openforis/ceo/local/JsonInstitutions.java, src/main/java/org/openforis/ceo/local/JsonPlots.java, src/main/java/org/openforis/ceo/postgres/PostgresPlots.java, src/main/resources/public/jsx/collection.js, src/main/resources/sql/load_ceo_functions.sql
=> allow admin to review plots

src/main/resources/public/css/custom.css, src/main/resources/public/jsx/home.js, src/main/resources/template/freemarker/home.ftl
=> changes to organize user institution and others

src/main/resources/public/jsx/widget-layout-editor.js
Resolves issue #90 Adds the available bands and placeholder tips for the user.
=> Display available bands when creating Geo-Dash widget

src/main/java/org/openforis/ceo/Proxy.java, src/main/java/org/openforis/ceo/local/JsonImagery.java, src/main/java/org/openforis/ceo/postgres/PostgresImagery.java, src/main/resources/public/css/custom.css, src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/review-institution.js
add feature profiles dropdowns to the securewatch imagery
=> add feature profiles dropdowns to the securewatch imagery

src/main/resources/public/jsx/widget-layout-editor.js, src/main/resources/template/freemarker/geo-dash-navbar.ftl
This closes #280 and allows users to copy the dashboard from any other project they have access to.
=> Enable dashboard configuration copy from another project

src/main/resources/public/jsx/create-project.js, src/main/resources/public/jsx/review-institution.js
=> aoi error using project template

src/main/resources/public/jsx/home.js
a single filter for both affiliations and other institutions
=> a single filter for both affiliations and other institutions

src/main/java/org/openforis/ceo/local/JsonProjects.java, src/main/java/org/openforis/ceo/postgres/PostgresProjects.java, src/main/resources/public/jsx/components/ProjectComponents.js, src/main/resources/public/jsx/review-project.js, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/update_2020-05-17.sql, src/main/resources/sql/update_2020-05-20.sql
=> allow review of project options

src/main/resources/public/css/geo-dash.css, src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/geo-dash.js, src/main/resources/public/jsx/widget-layout-editor.js
SAR integrated to degradation widget and added window name to collection page to eliminate navigation issue.
=> SAR integrated to degradation widget

src/main/resources/public/jsx/components/SurveyCardList.js
=> Change order of children with parent on survey card

src/main/resources/public/jsx/geo-dash.js
This addresses the lack of the map widgets staying in sync
=> fixed map sync

src/main/java/org/openforis/ceo/local/JsonPlots.java, src/main/java/org/openforis/ceo/postgres/PostgresPlots.java, src/main/resources/public/jsx/collection.js, src/main/resources/public/jsx/utils/textUtils.js, src/main/resources/sql/load_ceo_functions.sql, src/main/resources/sql/load_ceo_tables.sql, src/main/resources/sql/update_2020-06-10.sql, src/main/resources/sql/update_2020-06-10_csv_cols.sql
=> Allow more csv columns2

src/main/resources/public/jsx/collection.js
=> Fix quit button on the collection page

package.json, webpack.config.js, webpack.dev.js, webpack.prod.js
Single config file, pass env
Filter .map files
=> Webpack clean up

src/main/resources/public/jsx/geo-dash.js
This removes the Degradation tool buttons from the other map widgets that shouldn't have them.
=> removes degradation buttons from other map widgets

src/main/resources/public/jsx/geo-dash.js, src/main/resources/public/jsx/utils/geodashUtils.js, src/main/resources/public/jsx/widget-layout-editor.js
Adds the polygon compare tool requested for Clarke's research
=> Add polygon compare widget

src/main/resources/public/jsx/components/SurveyDesign.js
=> survey answer text validation

src/main/java/org/openforis/ceo/utils/ProjectUtils.java
=> Add some buffer to random distributions.

src/main/resources/public/jsx/unsubscribe-mailing-list.js
=> default value and new style for unsubscribe mailing list page

src/main/resources/public/css/custom.css, src/main/resources/public/jsx/home.js
=> new map toggle button

src/main/resources/public/jsx/components/PageComponents.js, src/main/resources/public/jsx/review-institution.js
=> missing institution logo fix

deps.edn, src/clj/org/openforis/ceo/handler.clj
=> Add session middleware and fix missing ring-gzip dependency.

src/main/resources/public/jsx/review-institution.js
=> added tab descriptions

src/main/java/org/openforis/ceo/utils/Mail.java
=> fixes mail issues with single and double quotes

src/main/resources/public/jsx/review-institution.js
=> imagery delete project btn

src/main/resources/public/css/custom.css, src/main/resources/public/jsx/home.js
=> info button -> visit button, toggle icon

src/main/java/org/openforis/ceo/utils/Mail.java
=> forced valid email address check, filtered not valid email address

src/main/resources/public/jsx/review-institution.js
=> added P and S buttons to download plot data and sample data

src/main/resources/public/js/mercator.js, src/main/resources/public/jsx/components/ProjectComponents.js, src/main/resources/public/jsx/create-project.js, src/main/resources/public/jsx/utils/textUtils.js
=> aoi coordinates editing

src/clj/org/openforis/ceo/database.clj, src/clj/org/openforis/ceo/db/plots.clj, src/clj/org/openforis/ceo/db/projects.clj, src/clj/org/openforis/ceo/db/users.clj, src/clj/org/openforis/ceo/utils/part_utils.clj, src/clj/org/openforis/ceo/utils/type_conversion.clj, src/clj/org/openforis/ceo/views.clj
database.clj
I like it.  Ive thought about something like that before but didnt really know it it was a "clean way" to do it.
=> review changes for helper files from Friday's review

src/clj/org/openforis/ceo/db/plots.clj, src/js/collection.js, src/js/create-project.js, src/js/home.js, src/js/project-dashboard.js, src/js/review-project.js, src/js/utils/mercator.js
=> Convert ceoMapStyles to a function to use as a style function

src/clj/org/openforis/ceo/db/institutions.clj, src/clj/org/openforis/ceo/db/projects.clj, src/sql/functions/member.sql
=> SQL authentication speedup

src/css/custom.css, src/js/home.js, src/js/utils/mercator.js
=> Update css for new OL methods

src/css/custom.css, src/js/collection.js, src/js/components/PageComponents.js, src/js/project/ManageProject.js
closes #321 
It looks like when we moved the imagery controls into their own components, the use of the spinner for planet daily was lost. However I didnt like where it was anyway.  If we want a loading message for Planet, lets rethink where it should go.
=> Add loading / saving / fetching plot message on collection page

src/js/project/PlotDesign.js, src/js/project/SampleDesign.js
=> Fix some typos

README.org, deps.edn, src/clj/org/openforis/ceo/server.clj
=> Update params for server

src/clj/org/openforis/ceo/db/plots.clj, src/clj/org/openforis/ceo/db/projects.clj, src/clj/org/openforis/ceo/utils/type_conversion.clj, src/js/collection.js
=> Fix bug for projects with no plot info

src/js/components/SurveyCollection.js
=> Fix error when deleting the first question

src/js/collection.js, src/js/project/SurveyQuestions.js, src/js/review-institution.js
=> Better error messages

src/js/widget-layout-editor.js
=> added a button to refresh basemap list

src/js/components/PageComponents.js, src/js/components/SurveyCollection.js, src/js/components/SvgIcon.js, src/js/home.js, src/js/project/CreateProjectWizard.js
=> moved svgIcons from utils to components and renamed into SvgIcon

src/css/custom.css, src/js/imagery/collectionMenuControls.js
=> fixed slider input type overlap

src/js/imagery/imageryOptions.js, src/js/review-institution.js
=> new validateParams logic

src/js/review-institution.js
now almost all the validation logic is inside one function.
=> moved MANDATORY validation logic inside validateParams

src/js/imagery/imageryOptions.js, src/js/review-institution.js
=> added sanitized logic, added wms url sanitizer function

src/js/imagery/imageryOptions.js, src/js/review-institution.js
=> "additional WMS params" sanitizer

src/css/custom.css, src/js/imagery/collectionMenuControls.js
=> improved imagery menus

src/js/imagery/collectionMenuControls.js
=> sentinel and planet imagery now have "Update Imagery" button

.gitignore, README.org, package.json
closes #915 
closes #914 
closes #929
=> More server cleanup

README.org, package.json, resources/public/locale/collection/en.json, src/js/geo-dash.js, src/js/imagery/collectionMenuControls.js
closes #920 
closes #921 
closes #922
=> Show optional production requirements

src/clj/org/openforis/ceo/db/projects.clj, src/sql/functions/project.sql
=> Intercept shp piping to get headers

src/css/custom.css, src/js/project/SurveyCardList.js
https://github.com/openforis/collect-earth-online/issues/998
=> Githika update tooltip

src/js/widget-layout-editor.js
=> now it updates only the widgets that have changed their layout

src/js/project/SurveyRules.js
https://github.com/openforis/collect-earth-online/issues/996
=> fixed rules by adding default option

src/js/components/PageComponents.js, src/js/geo-dash.js
=> added plot id information on geodash navigation bar

src/clj/org/openforis/ceo/db/plots.clj, src/clj/org/openforis/ceo/db/projects.clj, src/js/collection.js, src/js/components/SurveyCollection.js, src/js/project-admin.js, src/js/project/Overview.js, src/sql/dev_data/dev_data.sql
=> added plot confidence option and plot confidence slider

src/js/geo-dash.js
=> fixes geo dash infinite loop

src/clj/org/openforis/ceo/db/plots.clj, src/js/collection.js, src/js/project-dashboard.js, src/js/project/CreateProjectWizard.js, src/js/project/ManageProject.js, src/sql/functions/project.sql
There is no longer a need for a small max.  This should eliminate a lot of confusion.
=> Simplify project plots sql function

src/sql/functions/member.sql, src/sql/functions/project.sql, src/sql/functions/timesync.sql
=> changed "RETURNS TABLE" into "RETURNS table"

src/clj/org/openforis/ceo/db/projects.clj
=> Minor code refactoring in projects/dump-*-data functions

src/js/imagery/imageryOptions.js
=> added regex validation for url in xyz imagery type

src/js/review-institution.js
https://github.com/openforis/collect-earth-online/issues/642
Please let me know if this is what you explained in the other PR
=> not deleting last user

src/js/components/SurveyCollection.js
=> multi line error messages, added more instructions

src/css/custom.css, src/js/imagery/collectionMenuControls.js
=> fixed using code available in development branch

src/clj/org/openforis/ceo/db/projects.clj, src/sql/functions/project.sql
plots_ext_table is not update in projects when ext_table_count called so pass the information instead of trying to read it.
=> Update count function

src/js/geo-dash.js
=> Refactor code so that features are only build once

src/js/home.js
Replace unicode edit icon with 'EDIT' on the home page project list.
close #1077
=> Replace unicode edit icon with 'EDIT'

src/clj/org/openforis/ceo/db/users.clj, src/js/review-institution.js
This code adds the ability to send mail to the institution administrators when a member requested a membership.
fix #911
=> Send mail to the institution administrators for new member

src/clj/org/openforis/ceo/db/projects.clj, src/sql/changes/update_2020-10-28_remove_duplicate_user_plots.sql, src/sql/functions/project.sql
The main two accomplishments are
1. Untangle and optimize select queries
2. Have the clojure functions and sql match to reduce processing.
The output should be the same except for the remove of the analysis column which can easily be inferred by looking at the email column.
=> Clean up dump csv / sql

src/sql/changes/clean-old-data.sql, src/sql/changes/update_2021-01-15_sql_clean.sql
=> Add code to convert another type of question

src/clj/org/openforis/ceo/db/projects.clj, src/js/project/ManageProject.js
The information on the page was not updating for publish and close project.  
Fixes #1106 Fixes #1078
=> Return project back with publish

src/js/geo-dash.js
=> fixed wrong property pass

src/js/geo-dash.js
=> getArea works with Geometry, sqm to ha fix

src/js/register.js
Changes Registration form from "Subscribe to Mailinglist" to: "Subscribe to our mailing list"
Closes #1092
=> Change Mailinglist to Mailing List (#1092)

src/js/components/InstitutionEditor.js, src/js/project/Overview.js, src/js/project/SurveyQuestions.js
Adds max character lengths to the following:
- Institution Titles (400), URL (400), and Description (2000)
- Project Titles (400), Descriptions (2000)
- Survey Questions (210), Survey Answers (120)
=> Adds max characters to Institution/Project/Q&A inputs (#1094 #1095)

src/js/home.js
Centers "EDIT" text button for smaller screens (Closes #1116 )
=> Center Edit Text Button (#1116)

src/js/imagery/imageryOptions.js
=> wms url validation

src/js/components/SurveyCollection.js
Fixes #1125 
The checks were inclusive already.  The issue was that the numeric input was initialized to the same empty string as a text input.
=> Fix issue with number inputs not initializing correctly.

src/clj/org/openforis/ceo/db/projects.clj
=> Fix regex replace issue

src/js/geo-dash.js
=> geodash background imagery bug

src/clj/org/openforis/ceo/db/projects.clj, src/sql/functions/project.sql
=> Fix issue with user drawn samples and ext files

src/js/utils/mercator.js
Fix up linting errors in mercator.js
1. Move to arrow functions for unnamed functions (e.g. `function(params) { body }` to `(params) => { body }`)
2. Remove multi-line bodies that have a single return value (e.g. `(params) => { return body; }` to `(params) => body`)
3. Remove shadowed variables 
4. Use underscores to denote ignored parameters
=> Fix mercator.js linting errors

deps.edn, src/clj/collect_earth_online/build_db.clj, src/clj/collect_earth_online/convert_logos.clj, src/clj/collect_earth_online/database.clj, src/clj/collect_earth_online/db/geodash.clj, src/clj/collect_earth_online/db/imagery.clj, src/clj/collect_earth_online/db/institutions.clj, src/clj/collect_earth_online/db/plots.clj, src/clj/collect_earth_online/db/projects.clj, src/clj/collect_earth_online/db/users.clj, src/clj/collect_earth_online/handler.clj, src/clj/collect_earth_online/https.clj, src/clj/collect_earth_online/logging.clj, src/clj/collect_earth_online/proxy.clj, src/clj/collect_earth_online/routing.clj, src/clj/collect_earth_online/server.clj, src/clj/collect_earth_online/utils/mail.clj, src/clj/collect_earth_online/utils/part_utils.clj, src/clj/collect_earth_online/utils/type_conversion.clj, src/clj/collect_earth_online/views.clj
Shorten CLJ namespace from `org.openforis.ceo` to `collect-earth-online`
Fix #806
=> Shorten CLJ aliases to collect-earth-online

src/js/components/SurveyCollection.js
=> Add tool tip to survey question

src/clj/collect_earth_online/routing.clj
=> Remove security where not needed

src/js/components/PageComponents.js, src/js/reviewInstitution.js
Add alt texts to images to fix linting error
=> Add image alt tags

README.org
=> Add announcement.txt to readme

src/js/collection.js, src/js/components/SurveyCollection.js, src/js/utils/generalUtils.js
A few small changes unrelated to simple-collection
- move invert color to generalUtils
- Add comments for confusing code
- Add comment for unused code.
=> Matt pre clean work

.eslintignore, src/clj/collect_earth_online/handler.clj, src/clj/collect_earth_online/routing.clj, src/clj/collect_earth_online/views.clj, src/css/custom.css, src/js/collection.js, src/js/components/SurveyCollection.js, src/js/simpleCollection.js, src/js/utils/generalUtils.js, src/js/utils/mercator.js, webpack.config.js
This is a super slimmed down version of the collection page.  The usefulness is limited to surveys with:
- 1 question
- No rules
- 2-4 answers.
=> Matt slim down mobile

src/js/components/SurveyCollection.js, src/js/components/SurveyQuestionRules.js
Moves `getRulesById` from SurveyCollection to the SurveyQuestionRules component.
Fix #1188
=> Move getRulesById to SurveyQuestionRules

src/js/components/SurveyCollection.js
Update regex rule validation alert.
Fix #1075
=> Update regex validation text

src/js/collection.js, src/js/project/ManageProject.js, src/js/projectDashboard.js
Use the term 'Draft Mode' to describe projects that have not been published.
Fix #1074
=> Unpublished -> 'Draft Mode'

src/js/collection.js, src/js/utils/generalUtils.js
Fix the rest of the linter errors in collection.js
#1204
=> Move asPercentage, fix linter errors

.github/pull_request_template.md
=> CEO-129 Add PR Template

src/sql/default_data/default_data.sql, src/sql/dev_data/dev_data.sql
on-mailing-list field has been removed from the structure but not from dev and default data insert
Closes CEO-139
launch clj -M:build-db build-all and/or clj -M:build-db dev-data
=> sql mailing list fix

src/css/custom.css, src/js/project/SurveyRules.js
fix #1219 
Closes CEO-133
As an Admin, When I create or review a project, And I clicked on "Survey Rules", Then the New Rule section is renewed, responsive and working.
=> Rfontanarosa new rule form

package.json, src/js/geoDash.js
Upgrade Highcharts from version 8 to version 9.
Closes CEO-142
As an Admin, When I add a Time Series Graph widget, Then the Time Series Graph widget works on the data collection page
=> highcharts has been updated to version 9.10

src/js/account.js, src/js/collection.js, src/js/components/FormComponents.js, src/js/components/PageComponents.js, src/js/components/SurveyCollection.js, src/js/home.js, src/js/imagery/collectionMenuControls.js, src/js/institutionDashboard.js, src/js/login.js, src/js/passwordRequest.js, src/js/project/CreateProjectWizard.js, src/js/project/ImagerySelection.js, src/js/project/SampleDesign.js, src/js/project/SurveyCardList.js, src/js/project/SurveyQuestions.js, src/js/projectDashboard.js, src/js/register.js, src/js/reviewInstitution.js, src/js/simpleCollection.js, src/js/utils/generalUtils.js, src/js/utils/mercator.js
Clear some linter warnings for easier code review
=> A large amount of lint fixes

src/js/widgetLayoutEditor.js
Closes CEO-144
As an Admin, When I create or review a project, And I clicked on "Configure Geo-Dash", Then if there are widgets, they showed.
=> fixed bug: widgets didn't show properly

src/js/components/PageComponents.js
Add SERVIR Amazonia logo to about page.
Closes CEO-149
=> CEO-149 Add SERVIR AZ logo

src/clj/collect_earth_online/database.clj, src/clj/collect_earth_online/db/projects.clj, src/clj/collect_earth_online/routing.clj, src/sql/functions/project.sql
Use bulk insert statements for samples to improve time.
Example project with 30 plots and 100 samples went from 40 seconds to .5 seconds.
=> Bulk insert samples

src/clj/collect_earth_online/db/projects.clj, src/sql/functions/project.sql
Use bulk insert for plots.  Projects that took about 45 seconds to create now take less than 1.
Closes CEO-163
=> Bulk insert plots

resources/public/locale/collection/en.json, resources/public/locale/create-imagery/en.json, resources/public/locale/create-project/en.json, resources/public/locale/home/en.json, resources/public/locale/review-institution/en.json, src/js/components/PageComponents.js
Allows the help modal title to be set using the `title` attribute in the help locale files.
Closes CEO-156
=> CEO-156 Add slide titles for help modal

src/js/project/SurveyQuestions.js
Quick fix for Survey Designer.
=> Fix Survey Designer

src/js/components/SurveyCollection.js, src/js/project/SurveyCardList.js
Use the label "Placeholder" instead of "Answers" for Survey Questions of type input text/number.
Closes CEO-103
=> CEO-103 Use Placeholder for input questions

src/js/components/SvgIcon.js, src/js/project/CreateProjectWizard.js, src/js/project/ReviewForm.js, src/js/projectAdmin.js
Adds edit buttons to each section on the "Review Project" page.
Closes CEO-81
1. Given I am an admin, When I review a Project, And I click the edit icon in each section, Then I am taken directly to that page to edit that section.
=> CEO-81 Add edit sections to Project Review page

src/clj/collect_earth_online/db/institutions.clj
Display an error message when a user submits an empty title or descriptions for an institution.
Closes CEO-108
=> CEO-108 Show error message for required institution fields - backend

src/js/components/RulesCollectionModal.js, src/js/components/SurveyCollection.js, src/js/components/SurveyQuestionRules.js, src/js/components/SurveyRule.js, src/js/project/SurveyRules.js
Closes CEO-98
As an Admin, When I create a Project, And I add survey rules, Then I can see it and delete it from the Rules section.
=> new rule section

.gitignore, config.default.edn, deps.edn, src/clj/collect_earth_online/utils/mail.clj
Replaces mail-config.edn with the unified Triangulum config.edn
Closes CEO-178
=> CEO-178 Move mail-config.edn to config.edn

src/clj/collect_earth_online/git.clj, src/clj/collect_earth_online/views.clj, src/js/about.js, src/js/account.js, src/js/collection.js, src/js/components/PageComponents.js, src/js/createInstitution.js, src/js/geoDashHelp.js, src/js/home.js, src/js/institutionDashboard.js, src/js/login.js, src/js/pageNotFound.js, src/js/passwordRequest.js, src/js/passwordReset.js, src/js/projectAdmin.js, src/js/projectDashboard.js, src/js/register.js, src/js/reviewInstitution.js, src/js/simpleCollection.js, src/js/support.js, src/js/termsOfService.js, src/js/verifyEmail.js
Show the current branch/tag version in the Navigation Bar.
Closes CEO-70
=> CEO-70 Show Git tag/branch in Navigation Bar

README.org, config.default.edn
Remove some unused params from config.
=> Remove mail config used for mailing list

src/clj/collect_earth_online/db/projects.clj, src/clj/collect_earth_online/generators/clj_point.clj, src/clj/collect_earth_online/generators/external_file.clj, src/clj/collect_earth_online/utils/geom.clj, src/clj/collect_earth_online/utils/part_utils.clj, src/clj/collect_earth_online/utils/project.clj
A quick reorganization of the generator code.
=> Some organization of generators

src/clj/collect_earth_online/db/projects.clj, src/js/project/ReviewChanges.js
Show error messages when updating project.
Closes CEO-171 CEO-172
When updating a project, and I upload an invalid shp file, an error message shows in the ui.
=> Show error messages when updating project

src/js/project/PlotDesign.js, src/js/project/SampleDesign.js
Show the plot/sample file names in the Project Review page.
Closes CEO-176
=> CEO-176 Add plot/sample file names to review page

src/js/components/InstitutionEditor.js, src/js/components/RequiredInput.js, src/js/createInstitution.js, src/js/reviewInstitution.js
Add required field component to display error message when input has not been provided
Closes CEO-108
1. Given I am a user, When I go to add a new Institution, And I do not enter a Title or Description, Then I am presented with an error message.
Error message on Create Institution page:
Error message on Edit Institution page:
=> CEO-108 Show error message on required fields

src/clj/collect_earth_online/db/plots.clj, src/clj/collect_earth_online/db/projects.clj, src/js/utils/mercator.js, src/sql/functions/plots.sql, src/sql/functions/project.sql
Rename assigned to analyzed for consistency.
=> Rename assigned to analyzed

src/clj/collect_earth_online/db/plots.clj, src/clj/collect_earth_online/routing.clj, src/js/collection.js, src/js/simpleCollection.js, src/sql/functions/plots.sql
Step 1 in simplifying the navigation code before adding a bunch of new modes.
CEO-190
There are multiple navigation tests to run.  Check the master test script list.
=> Abstract out front end navigation code for simpler addition of new modes.

src/clj/collect_earth_online/db/plots.clj, src/sql/functions/plots.sql
Move navigation into CLJ so it does not need to be repeated for each mode.  This is pre work to add all of the new navigation modes.
Closes CEO-190
There are many navigation tests.  See the full test schedule.
=> CEO-190 Move navigation into CLJ so it does not need to be repeated for each mode

src/clj/collect_earth_online/db/plots.clj, src/sql/changes/update_2021-08-26_add_assigned_table.sql, src/sql/functions/plots.sql, src/sql/tables/all.sql
Add new table to assign users to plots
Closes CEO-69 and CEO-195
=> CEO-69 Add new table to assign users to plots

src/clj/collect_earth_online/db/projects.clj
Add back end changes for user assignment
Closes CEO-188
No testing yet since the UI is not created.  Can manually check if users are assigned by uncommenting 329
=> CEO-188 Add back end changes for user assignment

README.org, config.default.edn, deps.edn
Update triangulum and readme to use config for build-db
https://github.com/sig-gis/triangulum/pull/65
=> Update triangulum and readme to use config for build-db

src/js/collection.js
Adds border around navigation tools.
Closes CEO-220
=> CEO-220 Add navigation border

src/clj/collect_earth_online/db/projects.clj
This is part of the overlap QA/QC we missed the first round.
Closes CEO-218
Oh goodness, im not sure how to test this from the UI side. If you create a new project with 24 plots, 4 users, 3 times review and 50% overlap you should get 48 plot_assignments.
=> Update back end to accept number of times to review each plot

src/js/collection.js, src/js/project/QualityControl.js
Change step for qaqc slider to 5
Closes CEO-233
=> Change step for qaqc slider to 5

src/js/collection.js, src/js/utils/generalUtils.js, src/sql/functions/plots.sql
Clean up some things with user mode
- Remove error on new project
- Initialize current user after list comes
- update query for projects with qc 
Closes CEO-235, CEO-236, CEO-237, CEO-241
=> Clean up some things with user mode

src/clj/collect_earth_online/db/projects.clj, src/sql/changes/update_2021-09-24_rename_assigned_table.sql, src/sql/functions/plots.sql, src/sql/tables/all.sql
Rename assigned_plots to plot_assignments for clarity.
Closes CEO-231
=> Rename assigned_plots to plot_assignments

src/clj/collect_earth_online/db/plots.clj, src/clj/collect_earth_online/routing.clj, src/js/collection.js, src/js/userDisagreement.js, src/sql/functions/plots.sql, webpack.config.js
Add new disagreement page
Advances CEO-199
When collecting in qa/qc mode, and I click show disagreements, a window opens to show the disagreements.
=> CEO-198 Add new disagreement page

src/js/project/CreateProjectWizard.js, src/js/project/ManageProject.js, src/js/project/QAQCReview.js, src/js/project/ReviewForm.js, src/js/project/UserAssignmentReview.js, src/js/projectAdmin.js
Adds the User & QA/QC Assignments to the Project Review page.
Closes CEO-243
Equal User Method / SME Quality Method
Percent User Method / Overlap Quality Method
Equal User Method / None Quality Method
=> CEO-243 Add Users/QAQC to Review page

src/js/project/AssignPlots.js, src/js/project/PlotDesign.js, src/js/project/QualityControl.js
Shows the number of plots assigned to each user (in both Equal/Percent modes), and the number of plots for Quality Control (in both Overlap/SME modes).
Closes CEO-246
1. Given I am an admin, When I am creating a project, And I assign Equal as the User Assignment method, Then I can see how many plots each user will be assigned.
1. Given I am an admin, When I am creating a project, And I assign Percent as the User Assignment method, And I assign users and percentages, Then I can see how many plots each user will be assigned.
1. Given I am an admin, When I am creating a project, And I assign SMEs during the Plot Design stage, Then I can see how many plots each SME will be assigned.
1. Given I am an admin, When I am creating a project, And I assign Quality Control Overlap during the Plot …
=> CEO-246 Precalc # plots for Assignment/QAQC

src/clj/collect_earth_online/db/plots.clj, src/js/collection.js, src/js/userDisagreement.js
Use "disagreement" instead of "agreement" because this is the language Karen uses.
Closes CEO-252
This isnt particularly easy to test without knowing ahead of time what the disagreement should be.  We will need a standard project that is collected for testing.
=> Use "disagreement" instead of "agreement"

src/js/collection.js
=> CEO-268 Change User mode label to 'By User'

README.org
Move Iptables to dev doc readme
=> Move Iptables to dev doc readme

.gitignore, src/clj/collect_earth_online/views.clj
Copy announcement banner update from pyregence
1. When I create announcement.txt and add text, a banner shows up at the top of the page.
2. When the banner shows up and I click the x it hides
3. When the banner shows up and I wait 10 seconds, it hides itself.
=> Copy announcement banner update from pyregence

src/js/collection.js, src/js/components/Select.js, src/js/components/Switch.js
Clean up the Plot Navigation, use SVG icons.
Closes CEO-229
=> CEO-229 Cleanup Plot navigation

.github/pull_request_template.md
=> OPS-93 Update PR template

src/js/project/CreateProjectWizard.js
Validation should only run when "Overlap" QA/QC mode is selected.
Closes CEO-319
1. Given I am an admin, Then I can create a project.
=> CEO-319 Fix 'too few plots error'

src/clj/collect_earth_online/views.clj, src/sql/functions/plots.sql
Fix bug with blue dots for unanalyzed plots. 
Fix bug with announcement banner dismiss.
=> CEO-317 CEO-322, fix two bugs

src/clj/collect_earth_online/server.clj
=> Updates to match tri-80

src/clj/collect_earth_online/db/projects.clj, src/js/collection.js
Fix some bugs
1. Collect with user drawn samples, when adding a sample, and I save, and I go back to the plot, the drawn sample is there.
1. Collect with user drawn samples in draft mode, when publishing, there are no errors.
=> CEO-339 CEO-326 Clean up userdrawn samples to fix some bug

src/sql/changes/update_2021-11-24_add_user_created_date.sql, src/sql/tables/all.sql
Capture user registration date
=> CEO-282 Add user created date

src/sql/functions/project.sql
PlotId was not shown in the plot summary report.
1. On the review project page, Click "download plot data". 
2. The file should show plotid in the first column
=> CEO-330 Fix typo for plotid

.eslintrc.js, src/js/components/SurveyCollection.js, src/js/home.js, src/js/imagery/collectionMenuControls.js, src/js/passwordReset.js, src/js/project/Overview.js, src/js/project/PlotDesign.js, src/js/project/SampleDesign.js, src/js/projectAdmin.js, src/js/reviewInstitution.js, src/js/simpleCollection.js
Fix more lint errors.  We are close to none!
=> Fix more lint errors

README.org, package.json, src/sql/dev_data/dev_data.sql, src/sql/tables/all.sql
Updates the Readme, fixes out of date package.json scripts, and fixes SQL syntax errors. 
Closes CEO-346
Building the database from scratch and following the steps to get set up with a dev environment in the Readme now should work without throwing any errors.
=> CEO-346 Update the Readme, SQL files, and package.json.

src/js/home.js
The home page institution filters were not efficient for longer lists (ie as super admin)
=> Finally fix home page loading times

src/js/collection.js, src/js/components/RadioButton.js
Adds a new Radio Button component and uses it for the review mode.
Closes CEO-349
Toggling between Admin Review and Collect modes should work as before with the toggle switch.
=> CEO-349 Change review mode so that it uses new Radio Button component.

deps.edn, src/js/simpleCollection.js, src/js/utils/mercator.js
Merging local database changes from main into development.
=> Merging main into development 

src/js/reviewInstitution.js
Adds buttons to update a user's role and to remove a user from the institution. Confirms with the user before performing any updates to the selected user. Added small UI improvements to the Institution page.
Closes CEO-33
Updating a user's role should work properly and removing a user from the institution should work properly.
Before (smaller screen):
After (smaller screen):
Before (larger screen):
After (larger screen):
=> CEO-33 Don't automatically update a user's institution role.

src/js/reviewInstitution.js
Moves the delete institution button into the edit institution page. 
Closes CEO-369
Clicking the "Delete Institution" button from inside of the edit institution page should properly delete the institution.
=> CEO-369: Move delete institution into the edit page.

src/clj/collect_earth_online/db/projects.clj, src/clj/collect_earth_online/routing.clj, src/js/collection.js, src/js/imagery/collectionMenuControls.js, src/js/projectDashboard.js, src/js/utils/mercator.js, src/sql/functions/plots.sql, src/sql/functions/project.sql
Update stats so they show the same thing in both collect and review mode.
1. Go to the collection page, 
2. Click the project title, 
3. Stats should show  
2. They should include a project and "my" section
=> CEO-341 Change the way collection project stats are displayed

src/js/project/AssignPlots.js
Update messaging for assignment estimation for external files.  We cannot estimate the assignments at this time, so the messaging needs to reflect that.
1. Begin creating a project 
2. Select equal assignment for assigned users
3. Add at least one user
4. Toggle between the plot distribution types.
5. The messaging should reflect which distribution type is selected.
=> CEO-344 Update messaging for assignment estimation for external files

README.org, deps.edn, src/sql/dev_data/dev_data.sql
Update dev data and triangulum version to optionally load dev data on build.
`clojure -M:build-db build-all --dev-data`
=> Update dev data and triangulum version

src/js/project/CreateProjectWizard.js, src/js/project/PlotDesign.js, src/js/project/SampleDesign.js
Fix UI warning messages for plot and sample.
- Update sample count for circle plots
- Add new lines for warning messages
- Correctly check for max total samples separately than max samples per plot
(https://sig-gis.atlassian.net/jira/software/projects/CEO/boards/10?selectedIssue=CEO-371)
=> CEO-357 CEO-371 Fix UI warning messages for plot and sample

src/js/imagery/imageryOptions.js, src/js/simpleCollection.js
Updating development with the changes to main.
=> Merge main into development

src/js/components/FormComponents.js, src/js/geoDashHelp.js, src/js/home.js
A few more updates to make the two headers match.  Also, the original home caret direction was the correct one.
=> Update home header to match geodash

src/clj/collect_earth_online/db/institutions.clj, src/js/createInstitution.js
Fixes a bug where you didn't have to agree to the terms of use to create an institution. 
1. Create an institution without checking the terms.
2. You should be presented with an error message.
=> Fix a bug with institution creation (Dec testing bug fix).

src/js/components/FormComponents.js
Error on my part from #1434 . The caret was facing the wrong way.
=> UI fix for caret facing the wrong way.

README.org, config.default.edn
=> Update readme for session key

src/js/collection.js, src/js/components/SurveyCollection.js, src/js/imagery/collectionMenuControls.js, src/js/imagery/imageryOptions.js, src/js/project/AssignPlots.js, src/js/project/CreateProjectWizard.js, src/js/project/SurveyRules.js, src/js/reviewInstitution.js, src/js/simpleCollection.js, src/js/utils/generalUtils.js, src/js/utils/sequence.js
This is in preparation of creating a bunch more sequence functions from maps.
There are no code changes, just check the code to make sure all references are updated, and spelling is good.
=> Create a new sequence.js file and move existing functions

src/js/utils/sequence.js
Add object sequence functions to facilitate work with maps
Just a small unit test (unwritten) for each function
=> Add object sequence functions

src/js/collection.js, src/js/components/SurveyCollection.js, src/js/project/CreateProjectWizard.js, src/js/project/SurveyCardList.js, src/js/project/SurveyQuestions.js, src/js/project/SurveyRules.js, src/js/projectAdmin.js, src/js/simpleCollection.js, src/js/utils/sequence.js, src/sql/changes/update_2021-12-23_transform_survey_questions.sql
In order to be able to change text for a question, the question text has to be looked up each time instead of stored separately.
All tests pertaining to survey question design and survey collection.  Everything should function as it did before.
=> CEO-381 CEO-387 Transform survey questions to objects

README.org, src/js/widgetLayoutEditor.js, src/py/gee/utils.py, src/sql/dev_data/dev_data.sql
Removing a now outdated column in `dev_data.sql`, adding pointer cursors to GeoDash SVGs, updating the README, adding error handling to the call to `ee.Initialize()` so that you don't need a GEE account to compile.
Closes CEO-362
=> CEO-362 Small GeoDash cleanups.

src/sql/dev_data/dev_data.sql
Updates the `project_widgets` DB for `dev_data.sql`.
Closes CEO-363
Run `clojure -M:build-db build-all --dev-data` and go the GeoDash of the "Test Project". You should see 3 widgets there.
=> CEO-363 Update dev data with new widgets.

src/js/utils/generalUtils.js
Removes the now unused UnicodeIcon function.
Closes CEO-415
=> CEO-415 Remove the UnicodeIcon function

src/js/components/RulesCollectionModal.js, src/js/components/SurveyCollection.js, src/js/components/SurveyRule.js, src/js/project/SurveyCardList.js, src/js/project/SurveyRules.js, src/sql/changes/update_2021-12-30_remove_rule_keys.sql
We cannot change question / answer text if that value is stored instead of derived.
All existing functionality is the same.  Current survey rule BDD test should pass.
=> CEO-383 Remove rule question/answer text, and look up on load

src/js/collection.js, src/js/components/SurveyCollection.js, src/js/simpleCollection.js, src/sql/changes/update_2022-01-03_finilize_saved_answers.sql
Conform the existing projects so saved answers match the new form.
All functionality should be the same.
=> CEO-89 Finalize updates to saved answers for existing data

src/clj/collect_earth_online/db/projects.clj
Cleaning up after changing the survey_question / saved_answer format.  The returns the csv output to normal.
Check bdd scripts for downloading plot and sample csv files
=> CEO-385 Look up question and answer text before creating csv output

src/js/project/SurveyQuestions.js, src/js/project/SurveyRules.js, src/js/utils/sequence.js, src/js/widgetLayoutEditor.js
Bug fix.  I cant remember exactly witch down stream PR introduces the issue.
=> Create a unified next id function to fix issues with new answers

src/clj/collect_earth_online/db/projects.clj
For type input-text where the user can type in anything, we just show a 0 in the plot summary.  Instead, concatenate all of the unique answers.
1. Create a project with a multiple samples per plot and an question type input
2. Collect plot, for the input type question make sure to answer differently for different samples
3. Download the plot summary csv file
4. The column for the input question should contain concatenated answers
=> CEO-30 Stack answers for free text

src/clj/collect_earth_online/db/projects.clj
If the user changes the card order, the csv output would be in the wrong order.
1. Create a project with multiple question over different cards. 
2. Change the order of the cards
3. Download the sample csv output.  The question column order should match the survey question order
=> CEO-380 Tree sort questions so they show in the same order as the UI

src/js/components/RequiredInput.js, src/js/components/SurveyCollection.js
=> CEO-401 CEO-402 Allow RequireInput to not be required

src/js/project/SurveyCardList.js, src/js/project/SurveyQuestions.js
=> Fix two bugs with answers

src/clj/collect_earth_online/views.clj
Same as #1470, but for `main`.
=> Updating GA to remove query parameters.

src/js/components/SurveyCollection.js
Select a question by clicking anywhere inside the card.
Closes CEO-404
Clicking anywhere inside of a question will select the question.
=> CEO-404 Select question by clicking anywhere inside the card.

src/clj/collect_earth_online/db/plots.clj, src/js/userDisagreement.js
Finalize updates for the new survey question structure by updating the disagreement page.
1. Follow the BDD steps for the disagreement page.
=> CEO-405 Update disagreement page

README.org
Updates the README to use soft-wrap instead of hard-wrap. Each paragraph is now on its own line.
Closes CEO-416
=> CEO-416 Update the README to use soft-wrap instead of hard-wrap

src/js/collection.js, src/js/components/SurveyCollection.js, src/js/project/SurveyQuestions.js
Small bug with parent question answers not showing.
1. Create a new project.
2. Create a question with two answers (I used a button - text component)
3. Go to create a new question and select "Parent Question" to be the question you just created.
4. Click the Parent Answer drop down.
=> CEO-420 Fix issue with creating parent answer

README.org
=> MISC-59 Update copyright

src/sql/dev_data/dev_data.sql
=> Fix a few dev data issues

src/js/survey/NewAnswerDesigner.js, src/js/survey/SurveyDesignQuestion.js
Allow users to edit project questions and answers
1. Create a project with a question and a answer
2. Change the text in for the question or answer
3. Click save
=> CEO-428 CEO-65 Allow users to edit questions and answers

src/js/widgetLayoutEditor.js
Adds a message to a GeoDash dashboard with no widgets.
1. Create a new project.
2. Go to the GeoDash widget layout editor.
3. You should see a message telling you that you don't have any widgets.
=> Add a message to a GeoDash dashboard with no widgets.

src/js/survey/AnswerDesigner.js, src/js/survey/SurveyDesignQuestion.js
=> Just renaming a file to match its new use

src/js/survey/AnswerDesigner.js, src/js/survey/BulkAddAnswers.js, src/js/survey/SurveyDesignQuestion.js, src/js/utils/sequence.js
Allow users to bulk add answers and colors
2. Add an question, not type input
3. Enter color / answer pairs
4. Hit add
=> CEO-382 Allow users to add bulk colors and answers

src/js/components/RequiredInput.js, src/js/project/CreateProjectWizard.js, src/js/survey/AnswerDesigner.js, src/js/survey/SurveyCollectionAnswers.js, src/js/survey/SurveyCollectionPreview.js, src/js/survey/SurveyDesignQuestion.js
Add option for text input boxes to be required
2. Create a question type input
3. Set Text Required to checked (true)
4. The user should not be able to save a blank answer
=> CEO-403 Add option for text input boxes to be required

src/sql/dev_data/dev_data.sql
Fixes a bug where imagery couldn't be deleted due to an issue in the project_widgets dev data. Fixes that issue.
Closes CEO-429
1. Create a new institution.
2. Add some imagery.
3. Try to delete that imagery.
4. The imagery is deleted successfully.
=> CEO-429 Update dev data to fix imagery deletion bug.

src/js/survey/SurveyCollectionRulesModal.js, src/js/survey/SurveyDesignQuestion.js, src/js/survey/SurveyRule.js, src/js/survey/SurveyRulesList.js
Fix a bug.
1. Load a project with rules
2. Check that you can review, edit, and collect
=> CEO-434 Cant use context for SurveyRule, because its also accessed in collection

src/clj/collect_earth_online/db/projects.clj, src/js/project/Overview.js, src/sql/functions/project.sql
Filter public projects from templates by default.  The template list has too many useless public projects
1. Import live data so there is enough to use
2. Have / create at least one project in a institution
3. Go to the create project page
4. The template dropdown should only show institution projects
5. Check the Show Public Projects option
6. The template dropdown should show public projects
=> CEO-432 Filter public projects from templates by default

src/js/survey/NewQuestionDesigner.js
Allow users to copy questions, and optional their child questions.  You can stick the question with any parent question.  This allows you to only copy child questions to another card.
1. Create questions, some nested
2. Select "Copy Question" in the new question designer
3. Question(s) should copy with new name
=> Allow users to copy questions

package.json, src/js/components/InstitutionEditor.js, src/js/project/PlotDesign.js, src/js/project/ReviewChanges.js, src/js/project/SampleDesign.js, src/js/utils/generalUtils.js, src/js/utils/mercator.js, src/sql/changes/update_2022-01-27_update_boundary.sql, src/sql/tables/all.sql
Step 1 for CEO-5.  This uses a front end package to grab the first feature from a shapefile as the boundary.
2. On the plots step use radom and gridded
3. Click upload a shape.zip file for boundary -> the boundary should show in the AOI preview
4. Create the project
5. The plots should be in bounds of the geom
=> Allow user to upload shape file for project boundary (single feature)

src/css/custom.css, src/js/project/AssignPlots.js, src/js/project/ImagerySelection.js, src/js/project/ManageProject.js, src/js/project/Overview.js, src/js/project/PlotDesign.js, src/js/project/QualityControl.js, src/js/project/ReviewChanges.js, src/js/project/ReviewForm.js, src/js/project/SampleDesign.js
The wizard UI had mix of h2 / h3 / label / p being used wrong.  Update sections to have headers and slight indent.
=> Update header and block styling for wizard

src/clj/collect_earth_online/db/projects.clj, src/js/project/CreateProjectWizard.js, src/js/project/ReviewChanges.js, src/js/project/ReviewForm.js, src/js/survey/AnswerDesigner.js, src/js/survey/SurveyCard.js, src/js/survey/SurveyCardList.js, src/js/survey/SurveyDesignQuestion.js, src/js/survey/SurveyQuestionsDesigner.js
After the project is published, admins can fix typos in the survey questions but not add or remove questions.
1. Edit an existing, published project
2. Click on survey questions step
3. Only save button should show
1. Edit an existing, published project that has at least one answered plots
2. Click on survey questions step
3. Change question and answer text
4. Save updates
5. Download the sample CSV
6. The question and answer text should be updated in the project without erasing existing collected data
=> CEO-439 Allow users to edit just question and answer text after the project is published

README.org
Fixes some small README errors I noticed.
=> Small README fixes.

src/clj/collect_earth_online/db/projects.clj, src/js/survey/NewQuestionDesigner.js, src/js/survey/SurveyCard.js, src/js/survey/SurveyCardList.js, src/js/survey/SurveyCollection.js, src/sql/changes/update_2022-02-15_fix_card_order.sql
Fixes a bug with the new editable survey questions.  Changi the question id but keeping that as the key means the components dont update.
1. Create a project with two questions
2. Change the order of the questions
3. The order should change in the editor and help pane
=> CEO-454 Change the way survey cards are sorted

src/js/project/ReviewForm.js
Add edit buttons to the question section of the review project n published mode
1. Create a project 
2. In review, publish it 
3. Questions can be edited
=> CEO-453 Add edit buttons to the sections of the review project panel that are editable in published mode

src/js/project/CreateProjectWizard.js, src/js/project/Overview.js, src/js/survey/AnswerDesigner.js, src/js/survey/NewQuestionDesigner.js, src/js/survey/SurveyDesignQuestion.js
Use the ceo green and yellow instead of other colors in project wizard.
Closes CEO-###
=> CEO-444 Fix project wizard colors

src/js/project/AOIMap.js, src/js/project/CreateProjectWizard.js, src/js/project/PlotDesign.js, src/js/project/PlotStep.js
Make use of dropdown/selector to choose between input methods of plot boundary, depending on the choice the map can be active (when needed) or non-active with color cues and moving its instruction text position to bottom. 
1. In project Wizard, in Plot Design 
2. Select: Upload Boundary File 
3. The map section should change Color, loses interactivity, instruction message disappears
4. Select: Input Boundary Coordinates 
5. The map section should become normal, active with instruction message
=> CEO-443 Add a dropdown to select between file upload/manual selection for Boundary Coordinates

src/css/custom.css, src/css/geo-dash.css, src/js/collection.js, src/js/geodash/GraphWidget.js, src/js/geodash/StatsWidget.js, src/js/home.js, src/js/project/CreateProjectWizard.js, src/js/project/ReviewForm.js
Create global color vars instead of using hex values everywhere
=> CEO-455 Use global color vars for the CSS

src/css/custom.css
Fixes some css bg colors. 
Closes CEO-460
=> CEO-457 Some of the colors are not working correctly

README.org
=> CEO-459 auto validate documentation

src/css/custom.css, src/js/widgetLayoutEditor.js
-------
Change from bootstrap colors to CEO colors for action buttons. 
=> CEO-463 Update edit widget colors to official ones

src/js/survey/SurveyCard.js
-------
To allow for question reordering when editing project. 
Closes CEO-###
=> CEO-466 Fix survey questions reordering

src/js/widgetLayoutEditor.js
-------
Update base map refresh to select newly added element
Closes CEO-###
1. Add a new imagery to my Institution
2. Click "Refresh" in the GeoDash new widget dialog
3. The new item should appear in selection list
=> CEO-464 Fix base map list refresh

src/js/survey/BulkAddAnswers.js
Fix reported bug
2. Add an question, not type input
3. Enter color / answer pairs where colors are not hex
4. Hit add	
The user should get an error telling them that colors must be hex.
=> CEO-473 Check if bulk answer colors are hex before adding

src/js/project/ReviewChanges.js
1. Edit a project that is already published
2. Save changes
No warning message should appear
=> CEO-475 Update messaging for published projects.  Editing title wont clear saved answers

src/js/imagery/imageryOptions.js
-------
Use a consistent name for GEE Image Collection.
=> CEO-481 Inconsistent use of Image Collection and ImageCollection.

src/js/survey/SurveyDesignQuestion.js
-------
Dont show "Rules:" when there are none
=> CEO-480 Dont show "Rules:" when there are none

src/js/survey/SurveyRule.js
buttons
-------
Move hover remove rule button to the start
[Image 1 ](https://www.dropbox.com/s/suw37u6mfhw319z/Screen%20Shot%202022-03-11%20at%204.37.56%20PM.png?dl=0)
=> CEO-483 The remove button for rules should be at the beginning to match other remove

src/js/survey/NewQuestionDesigner.js, src/js/survey/SurveyCollection.js
I missed a section of code that needed to be updated from the survey questions data format change.
Follow the test scripts for Sum Of Answers and Matching Sums.
=> CEO-479 CEO-490 Finish updating rules check for object based questions

src/py/gee/utils.py
=> Fix json function and missing import

src/sql/dev_data/dev_data.sql, src/sql/tables/all.sql
=> Fix dev data for devs

src/py/gee/utils.py
Fix issue where Reducer.reduce will rename bands.
=> Reduce IC directly so the bands are not renamed

src/js/geodash/MapWidget.js
There is a little re-org.  The only code change was to append -2 the the end of the second dual image source so both sources load.
Create a dual imagery widget.  Collect, the slider should go between imagery.
=> CEO-497 Fix dual image layer not loading the second layer

src/js/survey/AnswerDesigner.js
Create a question type input.  Check text required.  The input box in the survey collection should show required.
=> CEO-485 Fix issue with "text required" option for input box

src/js/project/PlotDesign.js, src/js/project/SampleDesign.js
=> CEO-495 Show unknown instead of null

src/js/survey/SurveyCollectionAnswers.js
Create a project with input questions.  Collect. Go back to review plot.  Clicking on sample should show the last entered value.
=> CEO-484 Reset input text more often to fix missing values

src/clj/collect_earth_online/db/projects.clj
Bug fix
1. Create project with input type questions
2. Collect
3. Download samples
The values should be shown, not the placeholder
=> Default to :answer if exists for samples

src/js/geodash/DualImageryDesigner.js, src/js/geodash/MapWidget.js
=> Fix default slider position and messaging

config.default.edn, src/clj/collect_earth_online/proxy.clj, src/clj/collect_earth_online/routing.clj, src/js/imagery/collectionMenuControls.js, src/js/imagery/imageryOptions.js, src/js/reviewInstitution.js, src/js/utils/mercator.js
=> CEO-499 CEO-500 Get nicfi layers dynamically and proxy

src/js/project/AOIMap.js, src/js/project/CreateProjectWizard.js, src/js/project/PlotDesign.js, src/js/project/ReviewForm.js
Force the options list to just the public mapbox imagery
=> CEO-180 CEO-353 Only show mapbox on AOI design map

src/js/geodash/constants.js, src/js/widgetLayoutEditor.js
=> CEO-123 Add institution imagery widget

src/js/project/PlotDesign.js, src/js/project/SampleDesign.js
=> CEO-503 Use layout instead of list of components for more control

src/js/project/AOIMap.js, src/js/project/PlotDesign.js, src/js/utils/mercator.js
=> CEO-504 Show strata on wizard

src/js/geodash/constants.js, src/js/widgetLayoutEditor.js
=> Add institution imagery widget

src/js/imagery/imageryOptions.js
=> COM-125 Add 2022-03 Planet NICFI mosaic

src/js/imagery/imageryOptions.js
=> Add current NICFI months

src/clj/collect_earth_online/db/plots.clj, src/js/collection.js, src/sql/functions/plots.sql
Reverts openforis/collect-earth-online#1581
=> Revert "CEO-447 Block save if a new user has taken the plot lock"

.dir-locals.el, .gitignore, deps.edn, src/clj/collect_earth_online/db/projects.clj, src/clj/collect_earth_online/generators/external_file.clj, src/clj/collect_earth_online/server.clj
The issue is we were splitting by commas and then zipmaping them with headers, so it all depends on the position of column and (what is after it). If last, anything after first comma will be lost (if a field has commas as part of its string value) .  We now check for the this case and handle it before going further. 
Closes CEO-###
Projects > Project Creation
1. Create a new project.
2. When creating questions for the project, create a number of questions with commas in the question title and commas in the question answers.
3. Publish the project, and collect a few plots.
4. When collecting, make sure you answer some of the questions with the answers that include commas.
5. Go to the Project Management page and click the Download Plot Data and Download Sample Data buttons. 
6. Take a look …
=> Fix projects CSV input/output processing

src/js/geodash/TimeSeriesDesigner.js, src/js/geodash/form/GDSelect.js
=> Update timeseries bands/widgets

.github/pull_request_template.md, README.org, package.json, requirements-dev.txt, requirements.txt, src/py/tests/test_image_collections.py
Updates the README and other small cleanups.
Closes CEO-440
=> COL-440 Update README and other small cleanups

src/sql/changes/update_2022-04-16_remove_old_bk.sql
Removing the changefile that was applied in the 2023-04-07 deployment
=> Removing changefile from 2023-04-07 deployment

src/clj/collect_earth_online/db/doi.clj, src/clj/collect_earth_online/generators/external_file.clj, src/sql/changes/2023-04-29-create-doi-table.sql, src/sql/changes/2023-04-29-create-plots-and-samples-views.sql, src/sql/functions/doi.sql, src/sql/functions/member.sql
Added tables and functions to query tables for DOI.
Integration with Zenodos API for creating and retrieving a DOI and uploading files to it.
This is a proof of concept created to try out Zenodo's API.
Closes COL-419
=> COL-419 Feature/doi registration poc

src/js/collection.js, src/js/survey/NewQuestionDesigner.js, src/js/survey/SurveyCollection.js, src/js/survey/SurveyCollectionPreview.js, src/js/survey/SurveyCollectionQuestion.js, src/js/survey/SurveyDesignQuestion.js
New feature made to be able to hide survey questions on data collection.
Closes COL-478
Survey > Collection
Admin, User, or Visitor
1. Create a new project;
2. In the Survey questions designer, create a few questions and mark some with `Hide Question` (try with both child questions and parent questions);
3.  Go to data collection for that project.
4. Questions marked with `Hide Question` should not appear in the collection phase.
Questions marked with `Hide Question` should be hidden in the data collection stage.
If a parent question is marked with `Hide Question`, its child questions should not show up at all in data collection
=> COL-478 Hide question checkbox

src/js/collection.js, src/js/survey/AnswerDesigner.js, src/js/survey/NewQuestionDesigner.js, src/js/survey/SurveyCollection.js, src/js/survey/SurveyCollectionAnswers.js, src/js/survey/SurveyCollectionPreview.js, src/js/survey/SurveyCollectionQuestion.js, src/js/survey/SurveyDesignQuestion.js
Give the ability to the admin of the project to hide answers by checking a checkbox.
Closes COL-478
Admin, User, or Visitor
1. Create a  project;
2. On the survey part of the Wizard, create some questions and mark some of its answers to be hidden by checking the `Hide Answer?` checkbox and save the answer;
3. Verify in the survey preview that the answer is not present;
4. Go to data collection and verify that the answer checked for hiding is not present.
Answers checked to be hidden must not appear on the data collection section.
=> COL-478 Feature/hide answers

src/js/survey/SurveyCollectionAnswers.js, src/js/survey/SurveyDesignQuestion.js
Add more rules to hide questions.
Admin
=> COL - 478 hide questions survey rule

src/js/reviewInstitution.js
Hotfix for changing user role in an institution.
=> Fix newUserEmail check

src/js/geodash/MapWidget.js, src/js/utils/mercator.js
Reverts openforis/collect-earth-online#1639
=> Revert "COL-464: Fix NICFI images not loading when set to newest"

src/clj/collect_earth_online/db/doi.clj, src/clj/collect_earth_online/generators/external_file.clj, src/clj/collect_earth_online/routing.clj, src/sql/changes/2023-04-29-create-plots-and-samples-views.sql, src/sql/functions/plots.sql, src/sql/functions/project.sql
Finished DOI integrattion with zenodo
Closes COL-415
Project > DOI
Admin, User
1. Finish collecting data from a project;
2. Go to the project's page as an admin;
3. Click `Publish DOI` button;
4. Click `Get DOI` button.
DOI should be published and files should be downloadable (plot and sample shape files and the data file containing all data related to the project and the survey (by plot).
=> COL-415 Finished DOI feature

deps.edn, src/clj/collect_earth_online/db/doi.clj, src/clj/collect_earth_online/db/plots.clj, src/clj/collect_earth_online/generators/external_file.clj, src/clj/collect_earth_online/routing.clj, src/js/collection.js, src/js/geodash/MapWidget.js, src/js/utils/mercator.js, src/py/gee/routes.py, src/sql/changes/2023-06-05-add-constraints.sql, src/sql/functions/plots.sql, src/sql/functions/project.sql
=> Merge development into main Production 2023-07-14

src/py/gee/routes.py
Hotfix for removing the date default values for image collection assets
=> Hotfix: Removing date default values for image collection

src/js/project/PlotDesign.js, src/js/project/SampleDesign.js
Update language for uploading plot and sample CSV/SHP files.
Closes COL-327
=> COL-327: Changing language for uploading plot and sample details.

src/clj/collect_earth_online/generators/clj_point.clj, src/clj/collect_earth_online/utils/geom.clj, src/js/project/AssignPlots.js, src/js/project/PlotDesign.js, src/js/project/SampleDesign.js, src/js/survey/AnswerDesigner.js, src/js/survey/SurveyCollection.js, src/js/survey/SurveyCollectionAnswers.js, src/js/survey/SurveyDesignQuestion.js, src/js/utils/mercator.js, src/py/gee/routes.py
Preparing main branch for production deployment.
=> Merge development into main

src/clj/collect_earth_online/db/doi.clj, src/clj/collect_earth_online/routing.clj, src/js/project/ManageProject.js, src/js/project/Overview.js, src/js/projectAdmin.js
Merging hotfix into development branch
=> Fix/enable doi buttons (#1657)

src/js/collection.js
Fix issue reported by FAO, in which the answer was still being set even if it failed the rule check.
Closes COL-539
=> COL-539: Don't save if answers fail rule check

src/js/collection.js
Hotfix for conditional when validating rules in collection
=> Fixing conditional for checking rule

src/clj/collect_earth_online/db/users.clj, src/js/project/ManageProject.jsx, src/js/reviewInstitution.jsx
Merging changes from main to dev
=> Merge main to dev

config.example.edn, deps.edn, src/clj/collect_earth_online/handlers.clj, src/clj/collect_earth_online/routing.clj
=> Switch CEO to use triangulum.handler/authenticated-routing-handler

src/clj/collect_earth_online/db/users.clj, src/js/about.jsx, src/js/account.jsx, src/js/collection.jsx, src/js/createInstitution.jsx, src/js/geoDashHelp.jsx, src/js/home.jsx, src/js/institutionDashboard.jsx, src/js/login.jsx, src/js/pageNotFound.jsx, src/js/passwordRequest.jsx, src/js/passwordReset.jsx, src/js/projectAdmin.jsx, src/js/projectDashboard.jsx, src/js/register.jsx, src/js/reviewInstitution.jsx, src/js/simpleCollection.jsx, src/js/support.jsx, src/js/termsOfService.jsx, src/js/userDisagreement.jsx, src/js/verifyEmail.jsx
Git tag was not showing up on the website, this was due to a change in the keyword that triangulum passes to the frontend. This PR fixes that issue.
=> Hotfix: Fix keyword for tag in session

src/js/survey/SurveyCollectionAnswers.jsx
Hotfix for error when inputs are not required.
=> Fixing blank screen issue when text is not required

deps.edn, src/clj/collect_earth_online/generators/external_file.clj, src/sql/changes/2023-12-12-change-extra-infos-column-types.sql, src/sql/functions/plots.sql, src/sql/functions/project.sql
These changes were cherry-picked from development after testing was done. 
[PR to development with the descriptions.](https://github.com/openforis/collect-earth-online/pull/1707)
=> Hotfix: Keep the order of extra_plot_info and extra_sample_info

src/clj/collect_earth_online/db/geodash.clj, src/clj/collect_earth_online/proxy.clj
Fix cache max age time calculation to match comment
=> Fix cache max age for proxy and geodash

src/clj/collect_earth_online/workers.clj
Reducing worker timer from 1 hour to 30 minutes
=> Reduce timer to delete temp files

src/js/collection.jsx
This PR is intended to auto select samples if there is only one present
=> HOTFIX: Auto select single sample

src/js/survey/AnswerDesigner.jsx
Answers aren't getting their colors set, this impacted the project while interpreting the surveys. This PR fixes this issue
=> HOTFIX: answer colors when adding them in the project wizard

package.json, vite.config.js
Fix for failure on uploading SHP file as boundaries.
=> Return nodepolyfills to vite config

src/js/collection.jsx
Fix GEE script app. The former had broken graphs.
Closes COL-###
Collection > Side Panel > GEE Script
User
1. Create a project with gee scripts enabled
2. Navigate to the collection page and go to a plot
3. Click Show GEE Script button
The 4 imageries and 4 graphs should be visible in the new tab that opens
=> Change gee script app URL

src/clj/collect_earth_online/db/projects.clj
Fix issue introduced the last release where sub-questions would appear as new cards
=> Hotfix: Fix issue with sub-questions

src/clj/collect_earth_online/generators/external_file.clj
Fixes issues with project creation when using SHP and CSV files. The previous type conversion was incorrectly rounding the plot_ids.
=> Fix type conversion for external files

src/sql/functions/plots.sql
Fixes shapefile export in case a polygon is invalid.
=> Hotfix shapefile export

package.json
libraries for front-end testing and first front-end tests
Closes COL-557
run `npm run test` and `npm run test:coverage` to check it they are correctly working.
=> COL-557: Frontend testing

src/clj/collect_earth_online/db/projects.clj
- Wrap call-sql "create_project" in a try/catch
- Return error and 500 if error in create_project
=> Return 500 on error for create project

src/js/reviewInstitution.jsx
Promise.all was sending to catch if one of the requests failed.
=> Fix getProjectList where one promise rejects 

src/clj/collect_earth_online/db/doi.clj, src/clj/collect_earth_online/db/projects.clj, src/clj/collect_earth_online/db/users.clj, src/sql/changes/2025-03-31_edit_data_sharing.sql, src/sql/functions/member.sql, src/sql/functions/project.sql
Closes COL-877
Closes COL-882
1.
---
=> Working on changing SQL function and backend

src/clj/collect_earth_online/db/imagery.clj, src/clj/collect_earth_online/proxy.clj, src/clj/collect_earth_online/routing.clj, src/js/collection.jsx, src/js/geodash/GraphWidget.jsx, src/js/geodash/MapWidget.jsx, src/js/geodash/PreImageCollectionDesigner.jsx, src/js/geodash/TimeSeriesDesigner.jsx, src/js/geodash/form/BasemapSelector.jsx, src/js/imagery/collectionMenuControls.jsx, src/js/imagery/imageryOptions.js, src/js/register.jsx, src/js/reviewInstitution.jsx, src/js/simpleCollection.jsx, src/js/utils/mercator.js, src/js/widgetLayoutEditor.jsx, src/py/gee/inputs.py, src/py/gee/routes.py, src/py/gee/utils.py, src/py/tests/test_image_collections.py, src/sql/functions/imagery.sql
Repurposing NICFI functionality to TFO
Closes COL-###
Admin, User
1. Create a TFO imagery and add a TFO access token
2. Add this imagery to a project
3. Navigate to the project's collection page
4. Select the planet TFO imgery
5. Make sure the imagery is correctly displayed on the map
---
=> Switching from NICFI to TFO

deps.edn, src/clj/collect_earth_online/api.clj, src/clj/collect_earth_online/handlers.clj, src/clj/collect_earth_online/routing.clj
Adds a payload-validator middleware macro that analyzes incoming api requests for the adherence of their respective request payloads to a given malli schema.
Closes COL-897
- [x ] No new reflection warnings (`clojure -M:check-reflection`)
All
1. Log into the app. in the developer console, monitor the status of imagery apis such as "get-public-imagery"
---
=> Andy/col 897/imagery payload validation

src/clj/collect_earth_online/api.clj, src/clj/collect_earth_online/routing.clj
Extends the api request payload validation feature to cover geodash api. 
Closes COL-898
- [x ] No new reflection warnings (`clojure -M:check-reflection`)
GeoDash
User
1. Open an existing project and collect a sample for that project.
2. in the colleciton page, click the link to open the geodash.
3. in the new geodash tab/window, observe how everything works just fine. Open your browser console (eg, ctrl + shift + C on firefox) and reload the page.
4. open the 'network' tab of the browser console and see the request …
=> Andy/col 898/geodash api

src/clj/collect_earth_online/db/users.clj, src/js/register.jsx, src/js/verifyEmail.jsx
we were having a couple issues relatd to registration: the email link that was being sent to verify did not have a "/" character between the base-url (eg "ceo-dev.sig-gis.com" or "local.collect.earth:8080") and the "verify-email" route. second, that the action of completing registration resulted in no data-response. This would be fine as the email sent is the prompt but the frontend expects a success code in order not to report a false error to the user.
Closes COL-928, COL-957
- [ x] No new reflection warnings …
=> fixes data-response for registration and validation

src/js/reviewInstitution.jsx
Closes COL-938
Institution > Manage projects
Institution > Manage imagery
Admin, User
1. As an institution admin (or super admin), navigate to an institution
2. Check that the headers are present and make sense
3. Click the checkbox in the header, it must select every row
4. Try changing the visibility of the projects/imagery and see if it works.
5. Log in a non-admin and make sure the headers together with the bulk edit buttons are not present.
=> COL-938: Add headers with checkbox for select all for projects and imagery

src/clj/collect_earth_online/api.clj, src/clj/collect_earth_online/routing.clj
Closes COL-893
Projects
Admin, User
1. Try creating a project correctly, it should create it
2. Try creating an invalid project, an error modal should show up
---
=> COL-893: Projects schemas

src/clj/collect_earth_online/api.clj, src/clj/collect_earth_online/db/plots.clj, src/clj/collect_earth_online/routing.clj
Extends the malli-based api payload schema validation functionality to cover the /plots api.
Closes COL-895
- [x ] No new reflection warnings (`clojure -M:check-reflection`)
Collection
User
1. Log in and navigate to an existing project.
2. Collect a sample for that project.
3. When done collecting a sample, flag the plot.
---
=> Andy/col 895/api plots

src/clj/collect_earth_online/db/users.clj, src/clj/collect_earth_online/routing.clj, src/sql/functions/member.sql
Request from Aim4Forests stream to complete gateway with SEPAL: https://github.com/openforis/sepal/pull/348
=> Get Admin Institutions for given user for SEPAL gateway

src/clj/collect_earth_online/api.clj, src/clj/collect_earth_online/db/metrics.clj, src/clj/collect_earth_online/routing.clj, src/js/metrics.jsx, src/sql/functions/metrics.sql
=> Andy/col 980/metrics imagery

src/clj/collect_earth_online/api.clj, src/clj/collect_earth_online/db/metrics.clj
=> tweaks include metrics and api ns
