openforis/collect-earth-online

- src/main/java/org/openforis/ceo/Server.java
- src/main/java/org/openforis/ceo/db_api/Users.java
- src/main/java/org/openforis/ceo/local/JsonImagery.java
- src/main/java/org/openforis/ceo/local/JsonProjects.java
- src/main/java/org/openforis/ceo/local/JsonUsers.java
- src/main/java/org/openforis/ceo/postgres/PostgresProjects.java
- src/main/java/org/openforis/ceo/postgres/PostgresUsers.java
- src/main/java/org/openforis/ceo/users/OfUsers.java
- src/main/java/org/openforis/ceo/utils/ProjectUtils.java
- src/main/resources/public/jsx/account.js
- src/main/resources/scripts/data_migration.py
- src/main/resources/sql/load_ceo_functions.sql
UI work and JSON back end work to add user stats to the users page. The postgres api was updated to match the final format required for the UI.
The JSON back end would take to long to loop through every plot file every time so the user totals are stored with the project as the user saves a plot. Also a route '/update-project-user-stats' was created for an admin to re-calculate all of the user values to allow existing projects to be used when producing user stats.
Final data format:
{
"totalProjects": 14,
"totalPlots": 178,
"averageTime": 0,
"perProject": [
{
"id": 660,
"name": "Bangladesh_Hexagons_24oct18 + Bangladesh_square_24oct18 from Adolfo",
"description": "Just testing the Shapefile upload feature for Adolfo.",
"availability": "unpublished",
"plotCount": 4,
"analysisAverage": 0.0
} …
> Add userstats

- src/main/java/org/openforis/ceo/Server.java
- src/main/java/org/openforis/ceo/Views.java
- src/main/java/org/openforis/ceo/db_api/Users.java
- src/main/java/org/openforis/ceo/local/JsonImagery.java
- src/main/java/org/openforis/ceo/local/JsonProjects.java
- src/main/java/org/openforis/ceo/local/JsonUsers.java
- src/main/java/org/openforis/ceo/postgres/PostgresProjects.java
- src/main/java/org/openforis/ceo/postgres/PostgresUsers.java
- src/main/java/org/openforis/ceo/users/OfUsers.java
- src/main/java/org/openforis/ceo/utils/ProjectUtils.java
- src/main/resources/public/css/stylesheet.css
- src/main/resources/public/jsx/account.js
- src/main/resources/public/jsx/components/FormLayout.js
- src/main/resources/public/jsx/components/SectionBlock.js
- src/main/resources/public/jsx/create-project.js
- src/main/resources/public/jsx/institution.js
- src/main/resources/public/jsx/review-institution.js
- src/main/resources/public/jsx/review-project.js
- src/main/resources/scripts/data_migration.py
- src/main/resources/sql/load_ceo_functions.sql
- src/main/resources/template/freemarker/account.ftl
- src/main/resources/template/freemarker/create-project.ftl
- src/main/resources/template/freemarker/review-project.ftl
Update the projects UI to add checkbox option to use template plots and sample.
Update styling for some of the selectors on create project
During this process clean up the create-project and review-project files.
-- Remove circular logic
-- Do not store props in state if not mutating
-- More specific variable names
-- Remove more unused functions due to splitting the page into review and create
-- Update styling on review page to display information in a non-selectable state (ie no radio buttons)
-- Create external components for re-used code
-- Remove direct mutation of dom elements. Use inline ternary instead.
-- Use ternary instead of if blocks for conditional rendering.
Update routing for create-project, no ID is needed
Update JSON projects to create a project using plots from the …
> Add ability to use template plots and samples

- src/main/java/org/openforis/ceo/utils/ProjectUtils.java
- src/main/resources/public/jsx/collection.js
- src/main/resources/public/jsx/components/SurveyCardList.js
- src/main/resources/public/jsx/components/SurveyCollection.js
- src/main/resources/public/jsx/components/SurveyDesign.js
- src/main/resources/public/jsx/components/SurveyQuestions.js
- src/main/resources/public/jsx/create-project.js
- src/main/resources/public/jsx/home.js
- src/main/resources/public/jsx/project-dashboard.js
- src/main/resources/public/jsx/review-project.js
- src/main/resources/public/jsx/utils/SurveyUtils.js
Facing the user
- Prompt user on duplicate question and append enumerator 
-- Show in designer, hide elsewhere
- Validate project and survey before submitting.
-- Show selected file name on plot and sample design.
- Fix filter on home 
Behind the scenes
- Refactor convert survey values to survey quesions
-- Update to convert snake to camel
-- Add defaults for componentType and dataType
-- Force type for the few bad projects
-- Store result as `surveyQuestions` to distinguish good data and allow reference in the code
- Store surveyQuestion as selected instead of just text
-- Eliminates many conversions from text to id and back
-- Use .id everywhere that does not directly touch userSamples (still uses keys)
- Update create-projects page
-- Move map to life cylce
-- Use arrow functions
-- …
> Various UI fixes

- src/main/resources/public/jsx/create-project.js
Error was being thrown for templates which had shp files, when using copy template plots instead of uploading a new shp file.
> fix check logic for templates

- src/main/java/org/openforis/ceo/utils/ProjectUtils.java
if the plot size is the same of the sample resolution the gridded sample set will contain only one centered sample plot instead of four verticles sample points
> single centered sample point when plot size and sample resolution are the same

- src/main/resources/scripts/data_migration.py
Some data was out of sync with my test data where institution 1 was referenced by imagery but didn't exist.  This is no longer the case so update the migration script to work with test data.
> institution 1 seems to be ok now

- src/main/resources/public/jsx/collection.js
- src/main/resources/public/jsx/components/SurveyCardList.js
- src/main/resources/public/jsx/components/SurveyDesign.js
- src/main/resources/public/jsx/create-project.js
- src/main/resources/public/jsx/review-project.js
Modified getSelectedSampleIds in collection page to get sample ids for single points when they are not selected. This should fix the rule errors
> Githika add new rule

- src/main/java/org/openforis/ceo/postgres/PostgresGeoDash.java
- src/main/java/org/openforis/ceo/postgres/PostgresProjects.java
- src/main/resources/csv/csv2postgres.sh
- src/main/resources/scripts/data_migration.py
- src/main/resources/scripts/redo-dash.py
- src/main/resources/sql/load_ceo_functions.sql
A bad postgres api was deleting too many widgets. 
- Fix bad api
- Create script to re-add deleted widgets.
Handle null dash_id
Fix editable field on projects
Change plot_id to plotId for goto plots
Change "id" to "plot_id" in PostgresProjects
Update csv boudary logic
> fix postgres geodash delete

- src/main/resources/public/jsx/create-project.js
When you go to create project page and select a template project, it populates the fields. But, when you go back and select "None" in template project list. It does not take away the fields and bounding box. Fixed this!
> template bug

- src/main/resources/public/jsx/collection.js
Alert user of when no samples when plot is loaded or the user tries to answer a question.
Update life cycle hooks to not try to do any actions when no samples are loaded.
> Alert user of no samples

- src/main/java/org/openforis/ceo/local/JsonPlots.java
Use external plotId when available for getProjectPlot.  This makes the necessary changes to the JSON DB.
> update JSON to match PG changes

- src/main/resources/public/jsx/collection.js
The bug ended up being just line 1085 where `(surveyRule.questionSetIds1.includes(questionToSet))` should have been `(surveyRule.questionSetIds1.includes(questionToSet.id))`.  I went ahead and simplified this code a little.
> Fix bug when matching sum is answered in reverse order

- src/clj/org/openforis/ceo/db/plots.clj
- src/clj/org/openforis/ceo/utils/type_conversion.clj
Comments for the following PRs:
606 (FB Partial conversion of PostgresGeoDash.java)
609 (FB Convert PostgresPlots.java to plots.clj)
custom.css:
Section "GEO DASH PAGE" was removed. Were these styles moved somewhere else?
- Yes, a while ago Billy created geo-dash.css and didnt remove the styles he moved.
collection.js:
Lines *: Remove documentRoot from all fetch calls and don't pass it as a component parameter anywhere in this file.
Line 291: Update mercator.createMap to not take documentRoot arg.
- This is done in master. When its time to rebase/merge, these changes are successfully combined.
PostgresGeoDash.java -> geodash.clj:
Line 4: clj-http needs to be added to deps.edn.
- This was a little out of order, its added in the proxy PR where I used it first.
Line 16: :projectId -> …
> Monday changes (PR 606 / 609)

- deps.edn
ring/ring-defaults was importing ring/ring-headers and ring/ring-ssl for us.  we dont need ring/defaults with ring/ring-headers and ring/ring-ssl correctly imported.
> Update clojure packages

- src/js/project/CreateProjectWizard.js
Disabled buttons can be confusing.  There are also a few edge cases for when a user would be able to review the project that are not worth tracking.  Removing the disabled condition works smoothly because the code already verifies each step again before proceeding.
> Remove review condition

- src/clj/org/openforis/ceo/handler.clj
- src/clj/org/openforis/ceo/server.clj
I noticed that the handler stack for production has ssl-redirect, which means not having a cert with -m prod will still not work.  In looking at the two handler stacks, the only difference is ssl-redirect for prod, and reload for dev.
In your review of the run-server param updates you said
"Don't tie https to mode=prod. We specifically need to
be able to run production mode with http only on our Raspberry Pi.
This also makes it possible to test advanced mode compilation on our
local machines without https."
However, the back end does not have "advanced mode compilation". So we just need to use the production handler stack without ssl-redirect.  we will have to redefine the production handler stack to take a ssl? param.  Most of our middleware is the same in wrap-common handler.  We can …
> Update handler stack

- src/js/project/SurveyQuestions.js
JS does not fire an on change event for scientific notation, even though a number input allows it. Block this to avoid confusing error messaging.
> block scinetific notation for survey answers

- src/css/custom.css
- src/js/project/ManageProject.js
- src/js/project/SurveyRules.js
- src/js/utils/generalUtils.js
Errors fixed
- Missing or incomplete validations
- Example 1 many rules did not check to see if the selected question was valid
- Example 2 most of the comparisons for lists were insufficient to determine equivalency (i.e. [1].every(e => [1, 2, 3].includes(e)) is true but the two arrays are not equivalent)
- No messages to users.  Errors failed silently
- Silently mutating existing rules without warning the user
- Invalid handling of invalid ui events
- All of the form components did not have "value" set.  So if a UI change was invalid, the state did not update, but the UI was not reset to match the current (unchanged) state.
- State is not correctly reset when a change dictates.
- Example 1, when changing from rule type where the different rules share this.state.questionIds
- When …
> Clean up survey rule designer

- src/clj/org/openforis/ceo/db/plots.clj
- src/sql/functions/project.sql
This is a bug.  A SQL function was removed previously even though it was still being used.
> Add back removed SQL function that was still being used

- src/sql/changes/update_2021-02-22_fix_cross_project_imagery.sql
This issue does not seem to be persistent.  This PR does a one time reset of the invalid assignment.
close #1082
> Add SQL function to reset projects that incorrectly have other institution imagery

- src/clj/org/openforis/ceo/db/plots.clj
- src/sql/functions/project.sql
I added back a return type for the collection navigation function.  This time however its located in the function.sql file so it will be rebuild with 'build-db only-functions' without any extra steps.
closes #1033
> Simplify navigation SQL functions and add missing return value

- src/sql/functions/member.sql
Fixes #1100 
The SQL query for getting institution information incorrectly had institution_admin if the user was an admin of any institution.
> Fix SQL query for institution admin

- src/js/collection.js
Updates warning modal title and content to make clear changes will not
be saved. Modifies buttons to read "Yes I'm sure" with bright red button
to avoid confusion.
Closes #1076
> Unsaved changes warning modal (#1076)

- src/clj/org/openforis/ceo/routing.clj
- src/js/about.js
- src/js/support.js
- src/js/terms-of-service.js
- webpack.config.js
- Adds Terms of Service page (`/terms-of-service`)
- Links TOS page from About/Support pages
- Moved 'Disclaimer' from About page to TOS page
- Added Data Retention policy
Closes #1153
> Add TOS Page (master)

- .eslintignore
- .eslintrc.js
- .github/workflows/linter.yml
Enable running ESLint when new branches are pushed to the repo. 
1. Add linter workflow
2. Add .eslintignore file to prevent linting of `resources/**/*`, `.eslintrc.js` files
3. Move most of the common errors currently in our codebase to warnings, so the team can adopt the new style guidelines as they change files.
4. Tested with `mercator.js`
> Add ESLint runner

- src/clj/collect_earth_online/handler.clj
- src/clj/collect_earth_online/routing.clj
- src/js/simpleCollection.js
- webpack.config.js
This is for use for very specific external users.
Add new route /simple-collection, which is intended to be a very slimmed down version of the collection page.
Add new authentication that requires the projects token key.  This is to limit access to our external applications as best we can where their use of CEO allows for this narrow definition of a mobile site.
To access /simple-collection, you need the project token.  Query for it and then access the project like `http://local.collect.earth:8080/simple-collection?projectId=18770&tokenKey=4aff465d-d14f-4845-b4dc-2d17efe331e6`
> Add secret mobile route protected by token auth

- src/js/components/SurveyQuestionRules.js
- src/js/utils/generalUtils.js
Move displaying rules to the rules modal to prevent very long tooltips.
Fix #1190
2+ Rules
1 Rule:
No Rules:
> Move all rules to modal

- src/js/project/PlotDesign.js
Adds "Plot" to width / diameter when creating project to reduce confusion
Fix #1071
> Add 'Plot' diameter/width when creating project

- src/css/custom.css
- src/js/project/ImagerySelection.js
Adds 'Additional Imagery' to separate from the Default Imagery selector. Fixes up the spacing.
Fix #1070
> Add 'Additional Imagery' to Imagery selection

- src/js/project/AOIMap.js
- src/js/utils/generalUtils.js
When a User is on a Mac, the AOI Map screen instructs the user to "Hold CMD to select an Area of Interest"
Fix #1096
> AOI Map - Hold CMD for Mac OS

- src/js/institutionDashboard.js
`numProjects` was removed from the `get-institution-projects` endpoint, so it was not displaying. For the time being, sum analyzed and unanalyzed plots to get total plots.
Fix #1212
> Dashboard Total Plots (Fix #1212)

- src/js/widgetLayoutEditor.js
fix #1189
Available Bands was an hidden row, now it is always visible.
GeoDash didn't know the difference between an Image Asset or an Image Collection Asset, this caused errors when it requested for the Available Bands.
Instead of performing an http request to GEEG at onChange time, now the user have to click on the Refresh button to get the available bands for a specific Image Asset or Image Collection Asset.
> unavailable image asset fix and available bands refresh button

- src/js/components/SurveyQuestionRules.js
- src/js/utils/generalUtils.js
Now that we have more space for rules inside of the Rules Modal, optimize the format for each rule.
- Add truncate(text, max) fn
- Create components for each rule type
- Re-word the rules to refer to Answers
- Truncate long questions
- Italicize questions and and place in quotes
- Put RegEx constrain in `<pre>` tag
- Put answers in Badges
Fix #1182
Incompatible Answers
Text Match (Regex)
Exact Sums, Min/Max, and Matching Sums
(NEW) Tooltips for Long Answers
> Format Survey Rules

- src/clj/collect_earth_online/db/users.clj
- src/clj/collect_earth_online/routing.clj
- src/js/account.js
- src/js/login.js
- src/js/passwordRequest.js
- src/js/passwordReset.js
- src/js/register.js
- src/js/verifyEmail.js
- src/sql/changes/update_2021-05-26_user_email.sql
- src/sql/functions/member.sql
- src/sql/tables/all.sql
- webpack.config.js
Require new users to verify email so email notifications go out correctly.  Not seen here is that the smtp settings have been resolved for "no-reply"
Closes CEO-118 CEO-117
1. When a new user registers, then a message will show to notify the user that they need to verify their email
2. When a new user registers, then there is a link to verify their email in the welcome message
3. When a new user registers, and clicks the verify link, they are verified
4. When a new user registers, and tries to log in before verifying, they will not be able to
5. When a new user registers, and tries to login after verifying, they will be able to.
> Require new users to verify email

- src/js/geoDash.js
now geodash always includes visual parametrizations object in localstorage keys
Closes CEO-145
As a User, When collecting using GeoDash, Then widgets with different visual parameters are shown differently.
> fixed geodash Local Storage storageName issue

- src/sql/changes/clean-old-data.sql
- src/sql/changes/update-2021-06-07_set_default_created.sql
- src/sql/functions/project.sql
Finalize clean up scripts:
- Use last collected plot instead of project created date
- Ensure that old projects have a created, archived, and collection_start
- The first level of delete for projects leaves meta data (ie project row).  Delete meta data longer
Closes CEO-147
> Update clean up scripts

- src/js/collection.js
Fix UI issue.  When user is not on first question, and draws a new feature, going back to the questions make it look like the new feature is gone.
Closes CEO-148
1. When collecting with user drawn samples, and answered all questions, and draw a new feature, and go back to answer mode, then the new feature is still drawn.
> reset question tree to begining so new drawn points show

- src/js/collection.js
- src/js/project/ManageProject.js
Allow widget editor to open independently of the geo-dash.
Only windows that are trying to be repeatedly used need names.  The only case we have in CEO for that is the geo-dash during collection.
Closes CEO-146
- [ X] Commits include the JIRA issue and the `#review` hashtag (e.g. `CEO-### #review <comment>`)
- [X ] Code passes linter rules (`npm run eslint`/`clj-kondo --lint src`)
1. As admin, when the widget editor is open, I can collect on the same project without the geo-dash taking over the window.
> Update window names

- src/sql/changes/update_2021-05-26_imagery_UK.sql
We no longer allow duplicate imagery names.  Go back to older institutions and update the imagery title.
Closes CEO-28
> Change duplicate imagery title

- src/js/components/PageComponents.js
Show the help menu when a visitor first goes to the home page.
Closes CEO-113
1. Given I am a visitor, When I visit the CEO home page for the first time, Then I am shown the help menu screen.
> CEO-113 Show help menu on startup for home page

- src/css/geo-dash.css
- src/js/geoDash.js
- src/js/widgetLayoutEditor.js
- src/sql/changes/update_2021-06-06_simplify_widgets.sql
- src/sql/functions/project.sql
** Conform widget layout json
Widgets are always an array so there is no longer a need to check.
- See geodash.clj line 20
No widgets with a layout have a:
```
-- missing y
select widget->'layout' from project_widgets
where widget->'layout' is not null 
and widget->'layout'->'y' is null
-- i that is not already a string
select jsonb_typeof(widget->'layout'->'i') from project_widgets
where widget->'layout' is not null 
and jsonb_typeof(widget->'layout'->'i') <> 'string'
```
Widgets with layouts are cleaned to ensure no left over width or position fields
Widgets with grid row are converted to widgets with layouts
Widgets with width are put one on each row
** Bug fixes
updateAllServerWidgets was called before dashId was set in state so none of the old widgets -> new widgets were save if no …
> Clean up widgets

- src/js/geoDash.js
- src/js/reviewInstitution.js
- src/js/widgetLayoutEditor.js
- src/sql/changes/update_2021-06-07_clean_widget_imagery.sql
- src/sql/functions/imagery.sql
- src/sql/functions/project.sql
Clean up widget basemap key so it can be updated when an imagery is removed.
** Conform widget basemap
- Use key basemapId and value as integer
- Explicitly add to widget types that use it
- Use ID for osm layer instead of string
** Bug fixes
- Base map reverts to string "osm" after adding a widget or cancelling.  No need to change widgetBasemap when doing so.
** Behavior change
- We now have an explicit OSM type in CEO.  Users were previously accidently getting OSM if they did not update the base map option.  Moving forward, they will need to explicitly click it. However, the selected base map should stay selected through each widget being added.
Closes CEO-25
1. When I remove a institution imagery, the widget basemap reverts to OSM
> Clean up widget basemap

- src/js/collection.js
- src/sql/functions/member.sql
Fix bug where an institution member cannot flag a plot that does not have samples.
Closes CEO-150
1. Given I am an institution member, When I flag a plot with a reason, Then the plot is flagged.
> CEO-150 Fix flag plots without samples for members

- src/clj/collect_earth_online/db/projects.clj
CVS files dont load correctly if they contain a UTF-8 tag.
This file should load correctly for a new project.
[ceo-recheck-2021-07-13.csv](https://github.com/openforis/collect-earth-online/files/6816949/ceo-recheck-2021-07-13.csv)
> Remove utf tag from csv

- src/js/project/SurveyQuestions.js
Enables Flag Plot/Clear Answers in the Question Preview section when creating a project.
Closes CEO-82
1. Given I am an admin, When I am creating a project, And I add survey questions, And I answer the test the survey, Then I can "Clear All" answers.
1. Given I am an admin, When I am creating a project, Then I can "Flag Plot" in the test the survey.
Toggling "Flag Plot":
> CEO-82 Fix Clear Answers/Flag Plot in Survey Question Preview

- src/clj/collect_earth_online/db/plots.clj
- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/utils/type_conversion.clj
- src/js/collection.js
- src/js/components/SurveyQuestionRules.js
- src/js/geoDash.js
- src/js/simpleCollection.js
- src/js/utils/mercator.js
- src/sql/changes/clean-old-data.sql
- src/sql/changes/update_2021-06-28_retire_ext_tables.sql
- src/sql/create_db.sql
- src/sql/dev_data/dev_data.sql
- src/sql/functions/project.sql
- src/sql/tables/all.sql
Eliminate the use of separate tables for external data.
- For plots, reuse the logic we added for samples to allow user drawn.  That is that we dont need to store a center and a geom since center is a geom.  We can then just check for geom type.
- In this code, I use "generators" for each type of plot or sample, and and then uses bulk insert to copy the data to PG.  This should be more flexible moving forward. 
- Invalid external files fail before being imported into the DB
- The generators are quicker and potentially reusable for previewing the project in design.
- Eliminates redundant "recreate-samples"
- The DB PK and the visible plot id are now distinguished with obviously different var names.  All plots have a "visible_id".  If none is provided (ie a shapefile 'plotid'), then the …
> Eliminate the use of separate tables for external data.

- src/clj/collect_earth_online/db/imagery.clj
- src/js/geoDash.js
- src/js/imagery/imageryOptions.js
- src/js/reviewInstitution.js
- src/js/utils/mercator.js
- src/sql/changes/update_2021-06-08_no_proxy.sql
- src/sql/functions/imagery.sql
- src/sql/tables/all.sql
Make proxying optional for the existing proxiable imagery types.
Closes CEO-72
1. When creating / editing imagery, and select "proxy imagery", then the imagery is saved with that option.
2. When loading a wms source that is not proxied, then the url for the map tiles is not /get-tile
3. When loading a wms source that is proxied, then the url for the map tiles is /get-tile
> Make proxying optional

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/external_file.clj
- src/sql/changes/update_2021-06-28_retire_ext_tables.sql
- src/sql/changes/update_2021-08-17_ext_tables_restore.sql
- src/sql/functions/project.sql
- src/sql/tables/all.sql
Save external samples for restoring later.  This is only needed when allow-drawn-samples? is true.
Closes CEO-185
1. Create a project with "allow users to draw samples" and a shp file for samples.
2. As the admin click through some plots and draw samples and delete some of the existing shapes in the plot
3. Publish the project
4. The samples drawn should be gone, and the original shape should exists.
> Save external samples for restoring later

- src/js/components/InstitutionEditor.js
- src/js/components/RequiredInput.js
- src/js/components/SurveyCollection.js
Purpose
Prevent a user from saving a blank answer for text or number input questions. Shows an error dialogue and disables the save button.
Related Issues
Closes CEO-177
Submission Checklist
Commits include the JIRA issue and the #review hashtag (e.g. CEO-### #review <comment>)
Code passes linter rules (npm run eslint/clj-kondo --lint src)
Testing
Given I a visitor, When I am collecting, And I attempt to save an empty input answer, Then I am presented with an error.
> CEO-177 Use RequiredInput for survey collection inputs

- src/clj/collect_earth_online/db/projects.clj
- src/js/components/Select.js
- src/js/project/AssignPlots.js
- src/js/project/CreateProjectWizard.js
- src/js/project/PlotDesign.js
- src/js/project/SampleDesign.js
- src/js/projectAdmin.js
- src/js/utils/generalUtils.js
Adds fields to the Plot Design page for assigning plots to users.
Closes CEO-186
1. Given I am an admin, When I am creating a project, Then I can assign an equal or percentage of plots to users.
> CEO-186 Add Plot assignment fields

- src/clj/collect_earth_online/db/projects.clj
- src/js/project/AssignPlots.js
- src/js/project/CreateProjectWizard.js
- src/js/project/PlotDesign.js
- src/js/project/QualityControl.js
- src/js/projectAdmin.js
Adds QA/QC fields to the Plot Design page of the Project Wizard. 
Closes CEO-187
1. Given I am an admin, When I create a project, And I assign the Quality Control to "Overlap", Then a certain percentage of plots are assigned multiple times.
1. Given I am an admin, When I create a project, And I can assign the Quality Control to "SME Verification," Then the plots are assigned to SMEs to verify the plots.
> CEO-187 Add QA/QC fields

- src/clj/collect_earth_online/server.clj
Refreshes SSL Keystore every 60 seconds.
Closes CEO-212
> CEO-212 Refresh SSL Keystore every 60 seconds

- src/clj/collect_earth_online/generators/external_file.clj
Some csv apps add quotes around strings.  This would break
Closes CEO-155
1. Upload a csv file where the headers are wrapped in string (`"plotId", "sampleId"`)
> Parse quotes for CSV headers

- src/js/project/QualityControl.js
- src/js/project/SampleDesign.js
When QA/QC is enabled, disables the "None" sample distribution option and disables the User-Drawn samples section. Displays a message to describe why it's disabled.
When User-Drawn samples are enabled, also disables the Quality Control section and shows a message.
Closes CEO-210
1. Given I am an admin, When I am creating a project, And I enable a Quality Control method, Then I can no longer select "None" for my spatial distribution.
1. Given I am an admin, When I am creating a project, And I enable a Quality Control method, Then I can no longer enable User-Drawn samples.
1. Given I am an admin, When I am creating a project, And I enable User-Drawn samples, Then I can no longer enable Quality Control.
"None" spatial distribution disabled
User-drawn samples disabled, plus new error message
> CEO-210 Disable user-drawn when QA/QC is enabled, and vice-versa

- src/clj/collect_earth_online/db/projects.clj
Assign users additional plots based on the QA QC method.  The two implemented are user overlap and SME overlap.
Closes CEO-189
For this PR, you can uncomment test params on line 355
1. As admin, when I create a project with QA QC selected, additional plots are assigned to users.
> Assign QA QC users to assigned plots

- src/clj/collect_earth_online/db/plots.clj
- src/sql/functions/plots.sql
- src/sql/functions/project.sql
Allow multiple users to collect the same plot, which is needed for QA/QC
Closes CEO-7, CEO-196
To test, create a project with the test data for qa/qc.  Update the users so that you can log in as at least two of them.
1. As a user, I can collect plots that are assigned to me.
2. As a second I can collect plots that are assigned to me and user 1
3. As user 1 I can navigate through my collected plots that were also collected by user 2 and my results show.
> CEO-7 Allow multiple users to collect the same plot

- src/clj/collect_earth_online/db/plots.clj
- src/sql/functions/plots.sql
Instead of a second option for each 
Closes CEO-201
1. As and Admin, when I select admin mode, and I navigate through analyzed plots, I see all users plots
> Back end changes for navigation mode

- src/clj/collect_earth_online/db/plots.clj
- src/sql/functions/imagery.sql
- src/sql/functions/plots.sql
Adds "Flagged" to the navigation menu, enabling a user to view their flagged plots.
Closes CEO-191
1. Given I am a user, When I am on the collection page, Then I can navigate to my flagged plots.
> CEO-191 Add flagged plots to navigation

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
- src/js/components/Switch.js
- src/sql/functions/plots.sql
Adds the "Low Confidence" option to the navigation menu. Enables users and admins to navigate to low-confidence plots below a certain threshold.
Closes CEO-193
1. Given I am an admin, When I view a project, And I select "Low Confidence" navigation mode, And admin mode is enabled, Then I can view plots with confidence below the threshold.
1. Given I am a user, When I view a project, And I select "Low Confidence" navigation mode, Then I can view my plots with confidence below the threshold.
Admin:
User:
> CEO-193 Add Confidence nav mode

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
- src/js/components/Select.js
- src/js/project/AssignPlots.js
- src/js/project/QualityControl.js
- src/sql/functions/plots.sql
Enable viewing multiple user plots for admins. Adds a "User" selector when in admin mode and there are multiple plots.
Closes CEO-217
1. Given I am an admin, When I view a project, and I enable admin mode, And I view analyzed plots, Then I can switch between multiple users' plots.
> CEO-217 Add select plot by user to nav

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
Wrap navigation instead of hitting the end of a list
Closes CEO-226
1. When on the collection page, select any navigation mode, and I click next repeatedly, the plot number should increment until it hits the last plot and then the next plot should be the first sequentially for that mode.
1. When on the collection page, select any navigation mode, and I click previous repeatedly, the plot number should decrement until it hits the first plot and then the next plot should be the last sequentially for that mode.
> Wrap navigation instead of hitting the end of a list

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
Adds 'Natural' navigation mode to collection UI.
Closes CEO-202
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing an unanalyzed plot, And I click to the previous plot, Then I am shown my previously analyzed plot.
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing my first analyzed plot, And I click to the previous plot, Then I am shown the last unanalyzed plot.
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing my last unanalyzed plot, And I click to the next plot, Then I am shown the first analyzed plot.
1. Given I am a user, When I am collecting, And I select 'Natural' navigation mode, And I am viewing my last analyzed plot, And I click …
> CEO-202 Add 'Natural' navigation mode

- src/clj/collect_earth_online/db/plots.clj
- src/clj/collect_earth_online/routing.clj
- src/js/collection.js
- src/sql/functions/plots.sql
Adds 'User' navigation mode, which only navigates through a particular user's plots.
Closes CEO-219
1. Given I am an admin, When I view a project, And I select 'Users' navigation mode, Then I can navigate through a particular user's plots.
> CEO-219 Add 'User' navigation mode

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
- src/sql/functions/plots.sql
Adds 'QA/QC' mode to the navigation modes. Returns all plots that have more than 1 user assigned to them.
Currently, the concordance slider does nothing.
Closes CEO-194
1. Given I am an admin, When I am viewing a project, And I enable 'QA/QC' mode, Then I am shown plots with multiple users assigned, And that are within the concordance level.
> CEO-194 Add 'QA/QC' navigation mode

- src/clj/collect_earth_online/db/projects.clj
- src/js/project/CreateProjectWizard.js
- src/js/project/QualityControl.js
- src/js/projectAdmin.js
Adds input to enter # of Reviews (`timesToReview`). Validates that the `timesToReview` is always between 1 and the number of assigned users.
Closes CEO-228
1. Given I am an admin, When I am creating a project, and I assign "Overlap" as the QA/QC method, Then I can assign the number of times to review.
> CEO-228 Add timesToReview input

- src/js/project/QualityControl.js
Disables Quality Control selector when there are no assigned users. Adds a short warning message.
Closes CEO-227
1. Given I am an admin, When I am creating a Project, Then I cannot assign a Quality Control method until I have added assigned users.
> CEO-227 Disable QA/QC selector if no users are assigned

- src/js/project/CreateProjectWizard.js
- src/js/project/QualityControl.js
Fixes the following:
* Fix the error logic for `timesToReview`
* Adds a message for Subject Matter Experts (SME)
> Fix timesToReview logic, add SME message

- src/clj/collect_earth_online/db/plots.clj
- src/sql/functions/plots.sql
Filter QA/QC plots on agreement threshold for the qaqc navigation mode.
Closes CEO-221
When on the collection page, and my project has qaqc enabled, and more than one plot has been analyzed twice, then clicking next will got to the next plot where the answer to samples to not match with X% under the threshold.
For example if there are 10 plots and 5 are the same and 5 are different, then it should show in the navigation under 50%
> Filter QA/QC plots on agreement threshold

- src/js/project/AssignPlots.js
- src/js/project/CreateProjectWizard.js
- src/js/project/QualityControl.js
Disable QC based on none user assignment for when a user assigns some users and then goes back to none. 
Hide QC controls when none is selected but users where assigned
Closes CEO-234
1. Select equal assignment
2. add a user
3. select overlap
4. select no assignment
QC should go back to disabled with no controls showing.
> Disable QC based on none user assignment

- src/js/collection.js
Show "refresh" to admins in review mode
Closes CEO-245
On the collection page, in admin mode, the button next to the plot number says "Refresh".
On the collection page, in admin mode, when I change the plot number the button next to the plot number says "Go to plot".
> Show "refresh" to admins in review mode

- src/js/collection.js
EOM
Closes CEO-244
1. Given I am an admin, When I view a project, And the project has QA/QC enabled, Then I can select the QA/QC navigation mode.
> CEO-244 Only show QA/QC mode for Projects with QA/QC mode enabled

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
- src/js/utils/preferences.js
- src/sql/functions/plots.sql
Also changes the default behavior of "Review Mode" to only be enabled by default when a project has been "published."
Closes CEO-242
1. As an admin, When I create a project, And I leave it in Draft Mode, And I go to the project overview page, Then Review Mode is turned off by default.
1. As an admin, When I create a project, And I publish the project, And I go to the project overview page, Then Review Mode is turned on by default.
> CEO-242 Rename Admin Mode to Review Mode

- src/js/collection.js
- src/sql/functions/plots.sql
Show dropdown in admin mode so admin can see who answered what
Remove some repeat code.
Closes CEO-238
1.When in admin mode, every navigation mode shows a dropdown
2. When project has no qaqc, dropdown should be disabled
> Show dropdown in admin mode so admin can see who answered what

- src/js/project/CreateProjectWizard.js
Adds error message when too few plots have been assigned per user.
Closes CEO-207
1. Given I am an admin, When I am creating a project, And I assign plots, Then I must provide a minimum number of plots per user.
> CEO-207 Add lower limit plots per user

- src/js/project/CreateProjectWizard.js
Displays an error message for when User Assignment is "percent" and the percent assigned is 0%.
> Add error message when percent is 0

- src/clj/collect_earth_online/db/projects.clj
- src/js/project/ReviewChanges.js
Checks the User & QA/QC assignments, and updates the plots when either has been modified.
Closes CEO-215
1. Given I am an admin, When I am updating a project, And I change the User Assignments or Quality Control, Then I am warned that the collected plots will be deleted, And the plots are updated.
> CEO-215 Reset plots when assignments are updated

- src/js/collection.js
Show a unsaved changes warning when a user tries to hit "Back" and has unsaved answers.
Closes CEO-232
1. Given I am a user, When I am collecting, And I have unsaved answers, And I try to navigate away, Then I am shown a unsaved changes warning.
> CEO-232 Add unsaved changes warning

- src/js/project/AssignPlots.js
- src/js/project/CreateProjectWizard.js
- src/js/project/QualityControl.js
Filter out assigned users & assigned SMEs from the "possible users" that can be assigned to each. Also displays an error if a user is both an Assigned User and an SME.
Closes CEO-255
1. Given I am an admin, When I am creating a project, Then I cannot assign someone as both an assigned user and an SME.
> CEO-255 Filter out users/SMEs from possibleUsers

- src/js/collection.js
Rather than have a "Natural" navigation mode, use the label of "Assigned" when the project has assigned plots or "Default" when there are not assigned plots.
Closes CEO-254
1. Given I am a User, When I view a project with Assigned plots, Then I am shown the "Assigned" navigation mode by default.
1. Given I am a User, When I view a project without Assigned plots, Then I am shown the "Default" navigation mode by default.
Assigned Plots
No Assigned Plots
10-01 at 3 32 44 PM" src="https://user-images.githubusercontent.com/1829313/135692811-97596773-7f9f-4d3d-bf4b-d8d692a78f4a.png">
> CEO-254 Use Assigned/Default instead of Natural

- src/js/collection.js
Adds a confirmation when flagging plots that have existing answers.
Closes CEO-253
1. Given I am a user, When I am collecting, And I have answered some questions, And I flag a plot, Then I am presented with a warning that my answers will be cleared.
> CEO-253 Warn users flagging a plot will clear answers

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
Enable ability for admins to save over another user's plots.
Closes CEO-208
1. Given I am an admin, When I am reviewing a project, And I am in review mode, And I modify the sample answers, Then the sample answers are overwritten.
> CEO-208 Admin save over user plots

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/routing.clj
- src/js/institutionDashboard.js
- src/sql/functions/project.sql
Optimize query for institution stats.  The way the stats were queried were not appropriate for institutions with more than a few projects.  Instead of calling a separate API call for each project in the list, return the entire list together.
Prep for CEO-209 and CEO-288
1. As an admin, And I go to the institution dashboard, the list of projects with stats loads correctly.
Should look the same as before
> Optimize query for institution stats

- src/js/project/QualityControl.js
EOM
Closes CEO-267
1. Given I am a project admin, When I am creating a project, And I enable assigned users, And I set Quality Control to "Overlap", Then I can only set the # of reviewers to the number of assigned users.
> CEO-267 Set max timesToReview to number of assigned users

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/routing.clj
- src/js/institutionDashboard.js
- src/sql/functions/plots.sql
- src/sql/functions/project.sql
Update institution dash page to show stats for projects with qaqc.
Closes CEO-288
1. As admin, When going to the institution dashboard, the list of projects I see contains Assigned Users, Plot Assignments, and Partial Plots, in addition to the original columns
> CEO-288 Update institution dash page to show stats for projects with qaqc

- src/js/collection.js
- src/js/userDisagreement.js
Adds disagreement query parameter to `/user-disagreement` page, hide questions that have a disagreement lower than the provided value.
Closes CEO-261
1. Given I am an admin, When I am reviewing a project, And I enable QA/QC mode, And I set the disagreement threshold to 50%, And I view the Disagreement page, Then only questions with a disagreement higher than the 50% are shown.
> CEO-261 Add disagreement query param, hide Q's lower than disagreement

- README.org
Simplify the README by Replacing the HTTPS section with a link to the Triangulum instructions.
Added a section on running the app as a systemd service with a link to the Triangulum systemd section.
Closes TRI-68
> TRI-68 Replace HTTPS section with link, add Systemd section

- src/js/project/CreateProjectWizard.js
Use `intersection` rather than `union` to determine if there are common assigned users and SME's.
Closes CEO-322
1. Given I am an admin, When I am creating a project, Then I cannot assign someone as both an assigned user and an SME.
> CEO-322 Fix error where SME's could not be added

- src/js/project/CreateProjectWizard.js
Remove the QA/QC "Overlap" validation when using CSV/Shapfiles. CSV/Shapfiles are not parsed on the front-end, so we cannot determine the total plots.
Closes CEO-323
1. Given I am a user, When I create a project using a CSV/SHP file, And I add QA/QC mode of "overlap", Then the project can be created.
> CEO-323 Remove QA/QC validation for CSV/SHP files

- src/js/register.js
Adds an additional checkbox to user registration. Links to the NICFI Terms of Use checkbox which must also be checked before registering as a new user.
Closes CEO-327
- [x ] Included Jira issue in the PR title (e.g. `CEO-### <title>`)
- [x ] Code passes linter rules (`npm run eslint`/`clj-kondo --lint src`)
As a Guest, When I go to register as a new user, Then I cannot register until I accept both terms of use check boxes.
> CEO-327 Add NICFI Terms of Use checkbox.

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/clj_point.clj
Fix sample count for plots with round shape
1. Create project with round plots and gridded samples
2. Download samples file.
3. Sample IDs should be sequential
> Fix sample count for plots with round shape

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
- src/js/utils/mercator.js
- src/sql/functions/plots.sql
The uploaded or generated sample visibleId field would turn blank after saving a plot
1. Create a project with random or gridded samples. Allow user drawn samples,
2. Download the sample file and take note of the highest original sample id number (e.g. 1000 in a project with 100 plots and 10 samples per plot).
3. Collect, save one plot without drawing custom points and one with drawing custom points.
4. Download the sample data again.
5. Take a look at the sampleid column. All existing sample ids should keep their original id number while any newly drawn points should have ids that start with a number sequentially higher than the highest original sample id from step 2 (e.g. 1001 in our example).
> CEO-348 Pass through visible id so user drawn samples can maintain existing id

- src/js/project/AssignPlots.js
- src/js/project/QualityControl.js
- src/js/project/UserAssignmentReview.js
FIX For % user assignment, and many users, the percents are not assigned to the right user
1. Begin creating a project
2. Go to the plot step
3. Update settings to have some plots (ie random, plot count = 100)
4. Select assign users -> percentage of plots
5. Add users, they should be added most recently to the top
6. Assign several users percentages
7. Take a screen shot of the user percentages
8. Finish the wizard and go to review
9. Verify that the users listed are the same order and % as designed
> CEO-354 Fix user assignment order and percent assignment

- src/clj/collect_earth_online/db/projects.clj
- src/sql/tables/all.sql
Fix bug.  We must explicitly remove from user_plots because there is no FK constraint on user_samples
2. Collect in unpublished mode
3. Make changes to only the samples
4. After saving, the plot overview map should be all yellow dots again.
> CEO-358 FIX User plots are not cleared when samples are rebuilt

- src/js/project/AOIMap.js
ceoMapStyles("overview") changed and this call to it was not updated.
1. Create a project using a template
2. Go the the next step
3. The plot overview plots should be yellow.
> Update ceoMapStyles("overview") call in AOImap

- src/js/project/PlotDesign.js
- src/js/project/SampleDesign.js
Template file names were being displayed even if the user changed the distribution type.
1. Create a project with shp files
2. Create a new project with that as a template
3. Change distribution type to random
4. On the review page you should not see a file name.
> CEO-343 Use distribution to check for fname

- src/js/components/svg/SvgIcon.js
- src/js/project/ReviewForm.js
Adds prop types and default props to the SvgIcon component. Fixes an issue where the default value of `vertical-align: middle` conflicted with padding that was being added to the edit SVG in the review project page.
Closes CEO-375
All SVGs should look as they normally do.
> CEO-375 Add prop types and default props to SvgIcon.

- src/js/project/SampleDesign.js
Displays the selected sample geometries on the Project Review page.
Closes CEO-340
Create a project with user drawn geometries. You should see each selected geometry in the Project Review. Go back and edit the project such that you disable user drawn geometries. Now, in the Project Review page you shouldn't see anything.
> CEO-340 Display the selected sample geometries on the Project Review page.

- config.default.edn
- src/clj/collect_earth_online/views.clj
Add the Google Analytics tag to the site. You can find the scripts that I included on the Google Analytics website by navigating to Admin -> Data Streams -> ceo -> Add new on-age tag -> Global site tag (gtag.js)
Closes CEO-366
This is hard to properly test until deployed to production, but on the Reports Snapshot GA page I can see one user (myself) from using the site on localhost. We might need to figure out how to only track the actual production website since I wouldn't expect my visit to count.
> CEO-366 Add Google Analytics.

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/clj_point.clj
- src/sql/functions/plots.sql
There were a few errors generating random plots, and one with the samples.  
1. Some plots were out of bounds
2. The spacing was based on size of boundary so they were not generated close enough for larger projects.
3. Random plots could generated in the same location
Simplified some calcs with better reusability. 
Basically every test for gridded/random samples/plots.
> CEO-299 CEO-355 Better method for calculating gridded and random points

- config.default.edn
- deps.edn
- src/clj/collect_earth_online/handler.clj
Use a cookie store in ring for persistent log in.  This should limit disruptions for quick deployments.  Also its nice in dev when you are restarting the server every once in a while.
Note, im not sure why redis was recommended as it is a memory database and would reboot with the server.
1. Log in
2. Restart the server
3. Refresh the page
4. You should still be logged in
> CEO-372 Use a cookie store in ring for persistent log in

- src/js/components/FormComponents.js
- src/js/components/InstitutionEditor.js
- src/js/components/PageComponents.js
- src/js/home.js
Added a pointer cursor to the help icon and unified the UI on the Create Institution and Edit Institution cards to be consistent with the Log In card. Fixes a bug from #1432  where the right caret would show on the home page even if there were no projects in that institution. Adds `overflowY: auto` to the home page. Changes another location with caret icons to be consistent. 
Before:
After:
> Small UI fixes (Dec testing bug fix)

- src/js/collection.js
Adds ellipsis for longer project titles in the collection sidebar.
Closes CEO-392
1. Create a project with a long title.
2. Go to the collection page.
3. The project title should be cut off with ellipsis.
> CEO-392 Add ellipsis to project title component (Dec testing bug fix)

- src/js/projectDashboard.js
The number of plots on the Plot Dashboard didn't work. This PR fixes the logic.
Closes CEO-###
1. Create a project.
2. Collect with more than one user, flag some of the plots you collect.
3. Go to the project dashboard.
4. The number of plots you analyzed for each user (including those you flagged) and the total number of plots analyzed should all be correct.
Before:
After:
> CEO-398 Fix the number of plots in the Project Dashboard (Dec testing bug fix)

- src/js/project/CreateProjectWizard.js
- src/js/project/SampleDesign.js
Adds an error message directly in the Project Wizard UI when the sample spacing is too large for circle plots with gridded samples. 
Closes CEO-394
1. Create a project with circle plots and gridded samples.
2. Mess around with the sample spacing -- starting with a low number so that you don't get any error messages.
3. Now, change the sample spacing to be a large number.
4. You should get an error message in red telling you what the sample spacing needs to be and you shouldn't be able to proceed to the next Project Wizard step.
5. Change the sample spacing to be just below that number.
6. The text should be green now and you should be allowed to proceed.
> CEO-394 Add an error message for incorrect sample spacing with circle plots and gridded samples (Dec testing bug fix)

- src/js/project/ReviewForm.js
- src/sql/dev_data/dev_data.sql
Removes the Edit button from Survey Questions under Project Review when a project is published. 
Closes CEO-395
1. Create a project and don't publish it.
2. Go to the Project Review page and click on the edit button underneath Survey Questions.
3. It should take you to the proper page in the Project Wizard.
1. Create a project and publish it.
2. Go to the Project Review page and scroll down to the Survey Questions section.
3. There shouldn't be any edit button for you to click.
> CEO-395 Remove Edit button from Survey Questions when project is pulished (Dec testing bug fix)

- src/js/collection.js
Moves the Project Stats section underneath the new location of the info icon.
Closes CEO-393
> CEO-393 Fix the positioning of Project Stats (Dec testing bug fix)

- src/js/reviewInstitution.js
Doesn't allow for a user's role to be updated if the user's role hasn't changed in the input.
Closes CEO-397
1. Go to the Users tab of an institution. 
2. Change the role of a user to a different role.
3. Change the role of that user back to its original value.
4. Try to click the Update button for that user.
5. An alert warning you that you must change the user's role should pop up when clicking on it.
> CEO-397 Clean up the user assignment (Dec testing bug fix)

- src/clj/collect_earth_online/views.clj
Fixes an issue where only the first GA was loaded in.
1. Both GA scripts should be viewable in the `<head>` tag
> Fix Google Analytics (Dec testing bug fix)

- src/js/collection.js
- src/js/components/SurveyCollection.js
- src/js/project/SurveyCardList.js
- src/js/project/SurveyQuestions.js
- src/js/simpleCollection.js
- src/sql/changes/update_2021-12-23_transform_survey_questions.sql
- src/sql/changes/update_2021-12-29_rename_survey_keys.sql
We reference "parentQuestion" as a question object, which conflicts with the key "parentQuestion" in the question object. Using "parentQuestionId" for the key will clear confusion.
All survey pieces should work.
> Use "id" for id keys

- src/css/custom.css
- src/js/components/PageComponents.js
Adds a glow animation to the help button on page load. The icon will "glow" 2 times.
Closes CEO-361
Load a page with the help button. The button should "glow".
> CEO-361 Animate the help button on page load.

- src/clj/collect_earth_online/db/institutions.clj
- src/js/components/InstitutionEditor.js
- src/js/createInstitution.js
- src/js/reviewInstitution.js
- src/sql/changes/update_2022-01-11_add_image_name.sql
- src/sql/functions/member.sql
- src/sql/tables/all.sql
Adds an `image_name` column to the `institutions` database so that the file name of the logo that's uploaded can be displayed to the user. If no file has been uploaded, then "Choose image..." is displayed to the user.
Closes CEO-396
1. Create an institution.
2. Upload a logo.
3. You should be able to see the file name in the UI.
4. Go to the edit institution page. 
5. The same file name should still be there.
6. Change the logo to something else.
7. The new file name should be there the next time you go to edit the institution.
1. Create an institution without a logo.
2. Go to the edit institution page.
3. The UI should say "Choose image..."
> CEO-396 Display uploaded logo filename to the UI 

- src/js/project/CreateProjectWizard.js
- src/js/project/ReviewForm.js
- src/js/project/SurveyCardList.js
- src/js/project/SurveyRules.js
Fixes a few small bugs and makes two small UI improvements. 
Bug fixes:
1. The length of an object was being calculated in the wrong way.
2. Two error messages were not being calculated correctly.
3. New rules were being added with an ID of null, which caused a number of issues.
UI enhancements:
1. Added a pointer cursor to the different steps in the Project Wizard.
2. Added a separate section for Rules in Project Review (in anticipation of the Survey Rule Card PR).
Clicking on the edit button of the Rules section in the Project Review page takes you right to the Rules step in the Project Wizard. 
Adding rules works as expected.
> Some small bug fixes with Rules.

- src/js/project/SurveyRules.js
There were a few bugs with Incompatible Answers rules. The `IncompatibleAnswersForm` crashed the website when selected from the New Rule dropdown. You were also unable to create an Incompatible Answers rule with the first question that you had made (since it had an ID of 0).
You should be able to create an Incompatible Answers rule now.
> Fixed a bug where Incompatible Answers rules didn't work.

- src/clj/collect_earth_online/views.clj
Gets rid of the query params in Google Analytics.
I added the GA ID for collect.earth to my local `config.edn` file and visited the institution review page a few times. I now see `/review-institution` as its own row:
> Getting rid of the query params in GA

- src/js/components/SurveyRule.js
- src/js/project/SurveyCardList.js
- src/js/project/SurveyRules.js
Adds in rule IDs and an optional remove button the `SurveyRuleCard` component.
Closes CEO-101
The remove button should only show up in the Project Wizard and it should work normally. Without moving around the questions after creating rules, the Rule number for each survey question should line up with the Rule IDs in each card in the Project Review page.
> CEO-101 Add rule IDs and remove button to SurveyRuleCard.

- src/css/custom.css
- src/js/components/SurveyRule.js
- src/js/project/SurveyCardList.js
- src/js/project/SurveyRules.js
Replaces the tooltip content from each Survey Question Card and replaces it with a SurveyRule component. Small clean up with the logic for checking if a specific question includes a rule.
Closes CEO-410
When looking in the "Rules" section of a survey card and hovering over a Rule, you should see the Rule Card as a tooltip.
> CEO-410 Replace Rule tooltip with SurveyRule

- src/js/project/SurveyCardList.js
- src/js/utils/sequence.js
Fixes an old bug where swapping the order of survey questions in the Project Wizards wouldn't swap the rules properly. This would break any existing rules if a survey question was reordered, since it would always point to the same question ID/index. This PR adds code such that the question IDs inside of the `surveyRules` are updated properly every time a question is reordered in the Project Wizard.
Closes CEO-421
1. Create a new project with many different survey questions.
2. Create at least one rule of each type.
3. In the Project Wizard, use the up and down buttons to reorder the questions a bunch of times.
4. Each rule should stay attached to the question it is meant for.
> CEO-421 Fixing bugs with Rules when reordering questions.

- src/clj/collect_earth_online/generators/external_file.clj
Throw an error if there are duplicate header-keys in either SHP files or CSV files.
Closes CEO-426
1. Download the sample CSV file for either the plot or sample step.  
2. Add a new (duplicate) column. 
3. Try to create the project.
4. You should get an error and not be able to create the project.
> CEO-426 Check header-keys for duplicates and throw error.

- package.json
- src/js/components/Modal.js
Gets rid of `react-required-if` in place of `airbnb-prop-types`. Note that using the `airbnb-prop-types` package doesn't change our use of `PropTypes`. It simply adds a nice suite of custom `PropType` validators.  
Closes CEO-407
Delete the `confirmText` prop from `reviewInstitution.js/showDeleteImageryWarning` (line 525). Then try to delete an imagery. You should get an error in the console complaining about the prop type.
> CEO-407 Use airbnb-prop-types

- README.org
- src/js/project/AssignPlots.js
- src/js/utils/sequence.js
Shows the running total percent of plots assigned in the Plot Design. The text is red if the percents don't add up to 100%, and green if they do. 
Closes CEO-368
1. Create a project.
2. Assign at least two users using the "Percentage of plots" method.
3. Mess around with their percentages.
4. The running total percent should be visible at the bottom of the last user and the text should only be green once the total percent is 100.
> CEO-368 Show running total for percent plot assignments.

- src/js/geoDashHelp.js
- src/js/geodash/CopyDialog.js
- src/js/widgetLayoutEditor.js
Moves the widget title below the widget type selection when creating/editing a GeoDash widget. Updates the GeoDash help text to correspond with this change. Note that I didn't update the images on the GeoDash help page until it's decided if we want a GIF or an image. Swaps the position of the "Close" and "Copy" buttons on the "Copy Widget" modal to be consistent with the other GeoDash widget modals.
Closes CEO-430
> CEO-430 Move the widget title below the widget type selection.

- src/js/widgetLayoutEditor.js
Fixes the following bug:
1. Create a new project.
2. Go to the GeoDash widget layout editor for that project.
3. Try to add a widget (of any type).
4. Nothing happens when clicking "Create".
5. The console throws the following error:
```
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at _iterableToArray (iterableToArray.js?11b0:2:1)
at _toConsumableArray (toConsumableArray.js?448a:10:1)
at getNextInSequence (sequence.js?9d01:24:1)
at WidgetLayoutEditor.eval [as getNextLayout] (widgetLayoutEditor.js?dfe6:255:1)
at eval (widgetLayoutEditor.js?dfe6:312:1)
at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188:1)
at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237:1)
at invokeGuardedCallback …
```
> Fix a bug where you couldn't create a GeoDash widget.

- src/js/collection.js
- src/js/simpleCollection.js
- src/js/survey/AnswerDesigner.js
- src/js/survey/NewQuestionDesigner.js
- src/js/survey/SurveyCollectionPreview.js
- src/js/survey/SurveyDesignQuestion.js
- src/sql/changes/update_2022-01-24_parent_answers_array.sql
Allow users to select multiple parent answers
2. Add a question with many answers
3. Add a child question and select some but not all of the answers
4. The survey preview and the collection survey should only show the child question for the selected parent answers
> CEO-100 Allow users to select multiple parent answers

- deps.edn
- src/clj/collect_earth_online/server.clj
Adds `(notify/ready!)` once the server has started.
Closes TRI-78
Update the systemd unit file and restart the service using: `sudo clojure -M:systemd enable -r collect-earth-online -u ceo -d /opt/ceo/collect-earth-online`
> TRI-78 Add systemd notify after server start

- src/clj/collect_earth_online/db/projects.clj
- src/js/project/ReviewChanges.js
- src/sql/functions/plots.sql
Simplify update route to fix assignment issues.  We have reached critical mass on being able to only make changes based on specific setting changes.  This simplifies it to 3 possibilities:
1. The project is published and only non critical information can be updated.
2. Plot design is updated. Recreating the plots already resets everything else.
3. All other changes in draft mode will reset collected plots (completely re-create samples if the sample design changes)
User messaging is also simplified.
2. Changes many permutations of the settings (the bug was assignments not updating)
3. The project should update as expected
> CEO-427 Simplify update route to fix assignment issues

- src/js/project/CreateProjectWizard.js
- src/js/project/PlotDesign.js
- src/js/project/PlotStep.js
When use template plots is selected the review pane is shown.  This moves the assignment components outside of the plot designer so they are still shown.
1. Create a project with users assigned.
2. Create a new project with the first one as a template
3. On the plots tab, you should be able to adjust the user assignments without modifying the plot info
> CEO-423 Show user assignments when copy plots is selected

- src/clj/collect_earth_online/db/projects.clj
Fixes issue where overlapping qaqc did not work correctly for large number of collectors.
1. Create a project with 150 plots
2. Assign 10 users
3. Add 2x 100% overlap
4. Each user should have a total of 30 assigned plots.
> Cycle users better to fix overlap assign

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/clj_point.clj
- src/sql/functions/project.sql
Generate random and gridded plots using postgis.  This set us up to use arbitrary plot boundaries.
1. Create random and gridded plots like normal
2. The resulting plots should look as expected.
> CEO-25 Generate random and gridded plots using postgis

- README.org
Adds documentation for getting set up with a local copy of the live DB. Adds a section from example queries, though I'm not sure how useful the examples I provided are. If there are ones that are useful more in practice, let me know and I can add them.
Closes CEO-435
> CEO-435 Document how to get set up with a local copy of the live DB.

- src/js/survey/SurveyDesignQuestion.js
Hide the bulk add button of project questions when reviewing a project. 
1. Given an institution , and creating a project with at least one Question/Answer 
2. Click review 
3. Survey Question Card doesn't show the Bulk Add Button
> CEO-440 Remove the Bulk Add button when not in DesignMode. (Feb testing bug fix)

- src/js/utils/mercator.js
The loading message is confusing if the layer failed to load.
1. Create a institution imagery type GEE ImageCollection with some invalid inputs
2. Add to project
3. Collect that project, and select imagery
4. The message should read "source not found" instead of loading.
> CEO-449 Show a failed to load message for GEE imagery when it fails (Feb testing bug fix)

- src/sql/changes/update_2022-02-10_fix_fx_cascade.sql
- src/sql/tables/all.sql
We dont want projects or collected data to disappear when imagery is removed so we left on delete to restrict.  In the ui, when an imagery is removed, its really just archived.  However sometimes we need to delete data where on delete to restrict (removing an entire institution with delete from institutions... gets blocked if it added any imagery)
> CEO-451 Allow deletion of imagery to partially cascade by setting to null

- src/js/survey/BulkAddAnswers.js
The new answers are parsed, collected  and added all at once, preventing the bug where only the last one get added. 
1. In Survey Questions, after adding a survey question 
2. Click bulk add
3. Insert: #00FF00, green,#FF0000, red
4. The answers should be parsed, and all of them added
> CEO-446 Fix when adding color/answer pairs with Bulk Add, only the last pair is added

- src/css/custom.css
- src/js/geodash/CopyDialog.js
- src/js/widgetLayoutEditor.js
Use ceo green and yellow instead of bootstrap colors. 
Closes CEO-###
> CEO-445 Fix colors on the widget editor modal

- config.default.edn
- src/clj/collect_earth_online/db/users.clj
Add option to not send the welcome email if this flag is set.  Just set verified to true in the DB.
1. Copy config.default.edn to config.edn 
2. Set :auto-validate? in :mail map to true 
3. Run the app, register a new user 
4. A new user should register and validated
> CEO-450  Add optional flag in config.default.edn to auto validate emails (for devs without email set up)

- src/py/gee/routes.py
- src/py/gee/utils.py
JSON was being sent to the back end in different forms.  EE needs a dictionary, so always check type on the backend before sending to EE.
1. Go to an institution page 
2. Create a institution imagery type GEE ImageCollection with an invalid asset name and {} for vis params
3. Create a new project, and make sure to add that new invalid imagery to your project
4. Collect the project
5. Select the new imagery
> CEO-477 Fix issue with mismatched json

- src/sql/functions/project.sql
Fix bug where geodash with 1 widget would not auto launch
1. Create a project with Auto-launch Geo-Dash set
2. Add just 1 widget
3. Collect. 
The geodash window should pop up for each plot.
> CEO-472 Fix count for project having widgets

- src/js/geoDash.js
-------
In the geodash we had "Retrieving Geo-Dash configuration for
this project" instead of that "there is no geo-dash for the project" for 0
widgets.
> CEO-471 Fix geo-dash zero widgets message

- src/js/widgetLayoutEditor.js
Show entire preview widget in designer and shrink to fit when necessary.
> CEO-469 Alternative widget preview image rendering

- src/js/project/AOIMap.js
- src/js/project/PlotDesign.js
Fix a reported bug
For boundary type manual, you should be able to enter numbers that do not yet produce a valid boundary.  Upon entering a valid boundary, the project boundary should show on the map.
> CEO-488 CEO-489 Fix boundary input

- src/js/survey/SurveyCollectionRulesModal.js
EOM
Go to a project with rules.  Hover over the rule button.  No hover box should show.  You should still be able to slick and see the rules.
> CEO-491 The rule hover is too fast and can cover answers.  Remove

- src/js/geodash/GraphWidget.js
- src/js/utils/generalUtils.js
There was a mismatch between the image date displayed in the degradation widgets scatter chart and the date that was passed to the get image URL function. The mismatch caused Landsat images to not show up.  The JavaScript date was being coerced to the local time zone when the GEE image date in UTC milliseconds since epoch values were passed. 
Added function to force the date to stay in UTC.
```
// GEE image date 2000-01-11 in Mekong region.
var s = 947560246512
console.log(s)
console.log(new Date(s).toString())
console.log(new Date(s).toISOString())
>947560246512
>"Mon Jan 10 2000 21:10:46 GMT-0600 (Central Standard Time)"
>"2000-01-11T03:10:46.512Z"
```
Example illustrating the issue.
Closes CEO-506
> Switch from using dates to ISO date strings for the degradation widget.

- src/js/collection.js
- src/js/survey/SurveyCollection.js
- src/js/survey/SurveyCollectionAnswers.js
We allow for the sum check rule of questions to be run correctly. And also we allow for the user to see the answer of different plots when collecting and moving about. Previously the answers would not show on UI in the input field. 
Closes COM-###
1. Create a project with at least 2 questions with input of type number 
2. Add a sum rule for those questions (up to a number like 3) 
3. Start collecting on plots 
4. Input a number and then save it, move to the next plot 
5. Go back to the previous plot, the number inputed previously should still show up 
6. Go to next plot and save answer for it, such that its value combined with previous plot sums to bigger number set in the rule, hit save. 
7. You should see a popup telling you about the error, and giving you the constrained possible …
> SER-4 SumofAnswers rules bug and showing saved answers

- src/js/collection.js
- src/js/survey/SurveyCollection.js
- src/js/survey/SurveyCollectionAnswers.js
In JavaScript 0 is falsy and most inputs are strings, this patch is to handle such exceptions/assumptions and making sure the value passed to model logic is of the expected type.
Closes CEO-###
1. Create a sum rule of 100 
2. Create 2 questions of type Answer Button (has 0 as possible choice) 
3. Create an other questions of type input 
4. When collecting, put 0 in first, then 0 in second 
Should show alert about not satisfied rule (sum to 100)
> Fix zero and number input types in sum rule

- src/py/gee/utils.py
Updates `getTimeSeriesByIndex()` and `getLandSatMergedCollection()` to use Landsat Collection 2 rather than Collection 1. Collection 1 has been deprecated and no new images will be added. Additionally, adds Landsat 9 image collection. Small refactor to cloud masking procedure from differences in Collections.
Closes SER-2
GeoDash
1. Navigate to a CEO project and click Edit Project
2. Click Configure Geodash
3. In the widget layout editor, click Add Widget
4. Select the Time Series Graph widget
5. Add a title, set the date range to 12/31/2021 to 07/01/2022, then click create.
6.  Navigate back to the Edit Project tab and click Collect.
7. Click Go to first plot
8. Inspect the GeoDash.
Desired outcome: The time series graph includes data from 12/31/2021 to 07/01/2022
> SER-2 :Update to Landsat Collection 2, refactor cloud masking, add Landsat 9

- src/js/collection.js
There is a problem in some projects that has child questions that depend on conditions in parent answers, somehow gets duplicated and when going through collection, these duplicate child questions get checked if they have been answered or not and that prevents the user from saving the plot answers. This fix (initial) tries to skip over such questions and hopefully we get to tackle it at the root to not produce such duplicates in the first place when designing questions/answers. 
Closes SER-85
Collection 
1.  Create a project such as this one: https://collect.earth/collection?projectId=32124
(It has many questions that are children to parent questions) 
2. Collect and answer questions 
The plots should be saved
> SER-85 Fix saving question answers when duplicates get generated

- src/py/gee/__init__.py
- src/py/gee/utils.py
Added import utils to __init__ to allow for autocompletion in VS Code. This makes development and testing easier.
The statistics widget was not reporting elevation statistics for small plots (e.g. smaller than 100m2). The scale for calculating the statistics was set too high to compute anything for these areas. The solution is to have a smaller scale and add the bestEffort parameter.  bestEffort will adjust the scale of the computation to ensure it does not fail. 
Closes CEO-487
GeoDash
Test small plots return statistics.
1. Create a new project .
2. In Plot Design - Add a random distribution of 2 plots and set plot width to 1m.
3. In Sample Design - choose Center for sample distribution.
4. Create project.
5. Add a Statists GeoDash widget.
6. Navigate to the first plots GeoDash widget in …
> CEO-487 Statistics widget not reporting elevation and other stats.

- src/js/geodash/TimeSeriesDesigner.js
- src/js/geodash/form/GDInput.js
- src/js/geodash/form/GetBands.js
When a custom image collection is inputted we want it to auto populate the list with band names ("onBlur" and "onEnterKey") (as opposed to the current functionality where it's blank until the refresh button is clicked)
Closes CEO-###
> SER-297 Auto-populate the list with band names in Time series widget

- src/js/survey/NewQuestionDesigner.js
Fixing the survey card reordering -- the cardOrder attribute was not being set properly upon new question creation.
Closes COL-466
Survey & Rules > Card reordering
1. Create a new project
2. Create at least two questions
3. Try to reorder the questions
The questions should reorder appropriately.
> COL-466 Fix survey card reordering on new projects

- src/js/survey/NewQuestionDesigner.js
Fixes a bug introduced when trying to fix the survey card reordering: #1608 . Note that this re-breaks the survey card reordering bug (each survey card has a `cardOrder` of 0 and is not able to be reordered properly in the UI).
This is a duplicate of #1610 so that we can deploy the change to production.
Survey & Rules > Create new question
User
1. Create a question with a few answers.
2. Create a second question with the parent question set to the first question
3. Add some answers to the second question
4. Try to create a new question with new parents
The question from step 4 should be created properly.
> Hot fix to bug introduced in latest deployment

- src/clj/collect_earth_online/db/users.clj
- src/js/register.js
- src/js/reviewInstitution.js
- src/sql/changes/2023-04-17-lowercase-user-emails.sql
Make user emails lowercase for registration.
The email field for inviting a user to an institution is case-insensitive.
Added a `.sql` change to update all existing user emails to lowercase.
Closes COL-418
Institution>Members
Admin
1. Register as a new user with a mixed case email;
2. Make sure the email is lowercase.
1. Try inviting an existing user using some uppercase letters in the email.
2. Make sure the user is correctly invited and appears on the institution user's list.
All existing user emails should be lowercase after running the query.
New users' emails should be saved as lowercase.
Inviting a user to an institution is case-insensitive.
> COL-418 Lower case user emails on registration and adding to institution

- src/js/geodash/StatsWidget.js
- src/js/utils/mercator.js
Fix area calculation on stats widget and move it to `mercator.js`.
Closes COL-463
Geodash > Widget-Statistics 
Admin, User, Visitor
1. Create a project with a statistics widget in geodash;
2. Navigate to collection;
3. Verify the area is correctly calculated.
Have the correct area calculated in hectares.
> COL-463 Refactor code for calculating area in Stats widget

- src/js/survey/SurveyDesignQuestion.js
Added optional chaining to avoid breaking the project wizard when deleting an answer with child. 
Closes COL-468
Wizard > Survey questions
Admin
1. Create a new project
2. Go to the survey questions;
3. Add a question with some answers;
4. Create another question using one of the previous question's answers as a parent;
5. Delete the parent answer;
The page should no longer break when deleting a parent answer
> COL-468 Deleting a parent answer no longer breaks CEO

- src/py/gee/utils.py
This is a hotfix PR to solve a high-priority bug.
filterMetadata method expects an integer and was being passed a string, making the Sentinel-2 composition fail.
Though this is not the best fix for this issue, it is the lowest-impact fix for it. With more time, a proper fix will be implemented and tested on the development branch before going to main.
> Coerce type for cloud coverage in sentinel collection

- src/py/gee/utils.py
This is a hotfix PR to solve a high-priority bug.
filterMetadata method expects an integer and was being passed a string, making the Sentinel-2 composition fail.
Though this is not the best fix for this issue, it is the lowest-impact fix for it. With more time, a proper fix will be implemented and tested on the development branch before going to main.
> HOTFIX: Coerce type for cloud coverage in sentinel-2 composition

- src/js/survey/SurveyCollectionAnswers.js
Fix required number input not accepting 0 as an answer.
Closes COL-477
Survey & Rules > Collection
User, Visitor
1. Create a project with a number input checking the `Text Required?` checkbox;
2. Go to the collection page of the project;
3. Open a plot;
4. Fill the number input with 0;
5. Save the answer.
In order to make sure the correct answer was saved, enter the plot in Admin Review mode and check the answer for the plot.
CEO should save the answer as 0.
> COL-477 Fix required number input

- src/clj/collect_earth_online/db/geodash.clj
- src/js/geodash/MapWidget.js
- src/py/gee/routes.py
- src/py/gee/utils.py
Preloaded Image Collection Widget was not loading composite imagery for Landsat and Sentinel-2. This PR fixes the issue
Closes COL-###
Geodash > Widget - Preloaded Image Collections 
Admin
1. Create a Preloaded Image Collection for a project, choosing a composite imagery source, either Sentinel-2 or Lansat. Insert fields for start/end dates, bands, and cloud coverage;
2. Go to the collection page for the project;
3. Choose a plot and open the Geodash;
4. Composite imagery for this widget should load after 5 to 10 seconds.
Widget works correctly by loading the composite imagery for the desired source.
> COL-461 Bugfix/geodash preloaded images not loading

- src/js/project/CreateProjectWizard.js
Don't allow project admin to hide all answers to a question
Closes COL-478
Admin
1. Create a survey question to a project;
2. Create a few answers to it;
3. hide all questions;
4. try to go to the next step.
The user shouldn't be able to go to the next step if all answers for a question are hidden
> COL-478 dont allow to hide all answers

- src/py/gee/planet.py
- src/py/gee/routes.py
Planet API integration was not working due to using deprecated item_types as default values.
Closes COL-433
Imagery > Planet Daily
User
1. Select "Planet Daily" imagery.
2. Change any of the parameters and click "Update Imagery".
Images should load correctly
> COL-433: Fix Planet API integration

- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/external_file.clj
- src/clj/collect_earth_online/routing.clj
- src/js/project/ManageProject.js
- src/js/reviewInstitution.js
- src/sql/functions/plots.sql
Download shape files for a project as a zipped folder.
Closes COL-347
Projects > Shape Files
User
1. Go to an institution;
2. Click the button `Shape Files` for the desired project;
3. Accept the download for the `.zip` file
The user should be able to open the plot and sample shape files in a GIS software (e.g. qGIS).
> Download shape files

- src/js/geodash/MapWidget.js
- src/js/utils/mercator.js
When using Planet NICFI Imagery, when the user selected `newest imagery`  it would fail due to trying to pass `newest` as the mosaic name.
This PR fixes the issue by retrieving the newest NICFI mosaic layer before trying to get the imagery if it is set to `newest`.
Closes COL-464
Geodash > MapWidget
User
1. Create a geodash widget for a project using Planet NICFI as a basemap;
2. Navigate to the project collection page;
3. Go to a plot and open the geodash;
4. NICFI imagery should load.
NICFI imagery should load as a basemap
> COL-464: Fix NICFI images not loading when set to newest

- src/clj/collect_earth_online/db/projects.clj
User assignments were not being done when using a template project. This was due to only copying the plots from the template project to the current one, but not making the user assignments afterward.
This PR fixes this issue.
Closes COL-489
Wizard > Quality Control
Admin, User
1. Create a project with an arbitrary number of plots and samples (may or may not have users assigned and QA/QC set);
2. Use the project created in the last step as a template for a new project;
3. For this second project, assign users and set QA/QC;
4. Create the project;
5. Test in collection if the project respects the QA/QC.
QA/QC should work correctly when using another project as a template
> COL-489: Fixing issues with QA/QC when using a project template

- deps.edn
Bumping clojure version to 1.11.1
> COL-406: Bump clojure version

- src/py/gee/routes.py
Fix Image Collection Assets when passing visibility parameters as a list
Closes COL-508
1. Create an imagery for landsat using the GEE Image Collection Asset as the type;
2. Go to the collection page for a project that is using this imagery;
3. Change the imagery to be the one created in step one;
4. Image should load correctly.
> COL-508: Fix image collection assets bug

- src/clj/collect_earth_online/db/plots.clj
- src/js/collection.js
- src/sql/changes/2023-06-05-add-constraints.sql
Fix plot lock issue where it would allow two users to interpret the same plot.
Closes COL-491
Survey > plot collection
User
1. Create a project with samples and no user assignment;
2. log into two different accounts;
3. Try to interpret the same plot with them;
Interpreting a plot with two different accounts shouldn't be possible
> COL-491 fix plot lock issues

- src/js/survey/AnswerDesigner.js
- src/js/survey/SurveyDesignQuestion.js
If a user deletes a question or answer referenced in a rule, it breaks the collection stage. This PR implements a check before deletion, which disallows the user to delete questions/answers in case they are being used in a rule.
Closes COL-345
Survey & Rules > Survey
Admin
1. Create a project containing several questions and answers;
2. Add a few rules to some questions or answers;
3. Try deleting questions and answers with no rules; you should be able to delete them;
4. Try deleting questions and answers referenced in a rule; It should give an alert and not delete them.
Questions and answers not referenced in the rules should be deleted normally.
Questions and answers referenced in rules should not be deleted, and an alert should appear explaining.
> COL-345: Check rules before deleting questions

- src/js/survey/SurveyCollection.js
- src/js/survey/SurveyCollectionAnswers.js
In case the input text fails the rules check, return the answer to what it was before
Closes COL-408
Survey > Collection
User
1. Create a project with an input text/number that has a rule;
2. Go to the collection page;
3. Input a correct answer and save;
4. Input an incorrect answer and try to save.
After the rule fails, the answer in the text/number input field should return to its former value.
> COL-408: revert to previous answer

- src/js/project/AssignPlots.js
Changes confusing text when the `.shp` or `.csv` file contains plot distribution information for plot assignment.
Closes COL-482
> COL-482: change text for plot assignments

- src/clj/collect_earth_online/generators/clj_point.clj
- src/clj/collect_earth_online/utils/geom.clj
- src/js/utils/mercator.js
When drawing and creating plots and samples, the application wasn't considering the latitude, making polygons smaller the further away they were from the Equator.  This PR fixes this issue by correcting the measurements in EPSG:3857.
Closes COL-520
Collection > Plots
User
1. Create a project with either a circle or square plot, preferably in a place far from the Equator;
2. Start collection for the project;
3. Check for the size of the plot using the scale available on the map present on the collection page;
4. Export KML, use it in google earth, and measure the plot's side size or radius;
5. Open geodash and check that the plots are drawn correctly;
Make sure in steps 3 and 4 that the measurements match the plot size set in project creation.
> COL-520: Fix incorrect plot sizes

- src/js/collection.jsx
Don't jump to another plot if there are still interpretations to be reviewed.
Closes COL-522
Collection
Admin
1. Create a project that allows multiple interpretation of a plot;
2. Collect sample data with multiple users for the same plot;
3. Log in as a project admin or survey reviewer and start reviewing the interpretations;
4. the system should not jump the reviewer to another plot if there are still interpretations to be reviewed;
The app will only redirect the reviewer to a new plot if all the interpretations of the current plot have been reviewed, otherwise it will create an alert telling the user that there are still interpretations to be reviewed.
> COL-522: Multiple interpretation review

- src/js/geodash/DegradationDesigner.jsx
- src/js/geodash/DegradationWidget.jsx
- src/js/geodash/TimeSeriesDesigner.jsx
Added options to Degradation Wizard and Time Series Graph Widgets: [NDVI, NBR and NDWI] and [NBR] respectively.
Closes COL-###
GeoDash
Admin
Choose existing project and navigate to the GeoDash configuration page. Create a Time Series Graph and Select "NBR" as the band. Then create a Degradation Tool Widget and select either "NDVI", "NDWI", or "NBR" as the graph band. T
1.
New widgets appear in the database with the aforementioned graph band options.
> adds NBR, NDWI, NDVI to widget options

- src/js/collection.jsx
- src/js/utils/kml.js
- src/js/utils/mercator.js
Closes COL-###
Projects
Admin
1. When logged in as an admin, navigate to a project under an institution. From there, Navigate to a Plot feature, such as by clicking "go to first plot."
2. Download the KML for the project plot by clicking "download plot kml." It is recommended to right-click this button and select "save link as" to facilitate retrieval of exported data. note the destination directory and filename of exported KML file.
3. open a KML browser (such as [Google Earth](https://earth.google.com/web/)).
4. In the case of Google Earth, open the "projects" sidebar from the options to the left. It's probably third from the bottom.
5. Use the "open" > "import KML file from computer" dropdown menu to select the KML file from step 2.
---
6. Note the Ring around the plot sample features, …
> Inject StyleNode to KML

- src/js/components/Select.jsx
- src/js/components/UserSelect.jsx
- src/js/imagery/collectionMenuControls.jsx
- src/js/utils/validation.js
- src/py/gee/routes.py
Added the reducer options in the collection page so the users can change it during interpretation.
It is now possible to leave the end date empty in order to grab imagery information from the date set of the start date field
Closes COL-513
collection > imagery selection
User
First test:
1. Start collecting a project that has either sentinel or landsat imagery enabled;
2. Remove the value from end date;
3. Imagery shown should be only from the specific date set on start date.
Second test:
1. Start collecting a project that has either sentinel or landsat imagery enabled;
2. Change the reducer type and set start and end dates;
3. Check that the imagery shown is correct according to the parameters;
> COL-513: Add combinatorial imagery for interpretation page

- src/js/survey/SurveyCollectionAnswers.js
Dropdown questions were not functioning correctly, due to the current answer not being sent to `setCurrentValue` (this is now required after changes done to that function).
Closes COL-542
Survey > Dropdown questions
User
1. Create a project with dropdown questions;
2. go into the collection page and answer the dropdown questions.
Answering the dropdown questions should work correctly, setting the answer field with the correct selection.
> COL-542: Fix dropdown survey questions

- src/js/components/RequiredInput.jsx
- src/js/survey/SurveyCollectionAnswers.jsx
In cases where input text is required and the textbox is clicked on, an undefined value caused a typerror. Reported by Aurelie Shapiro. 
Needed to manually set values for required and touch variables since this is a case where answerText was undefined. 
Admin
Try a required text input field and saving the answer after clicking on the text box in a case where allSamplesMatch = false.
https://github.com/openforis/collect-earth-online/assets/47796239/e2e7063f-7f26-46eb-b72c-51b1724bc9d7
> Blank screen for required text

- src/js/imagery/collectionMenuControls.jsx
Add buttons to move through NICFI imagery. 
Requested by Aurelie Shapiro.
No related Jira 
Deployed in local environment tested there
User?
Go to collect view, select Planet NICFI imagery, try both buttons.
Users able to move through Planet NICFI imagery without having to select from dropdown. 
https://github.com/openforis/collect-earth-online/assets/47796239/5532897d-7566-4c59-83cb-8da3d8979bd6
> Add buttons for Planet NICFI Imagery

- src/js/geodash/MapWidget.jsx
- src/js/geodash/TimeSeriesDesigner.jsx
- src/js/geodash/form/BasemapSelector.jsx
- src/js/widgetLayoutEditor.jsx
- ## Purpose
Adds a date selector to NICFI-based imagery when using the "Imagery Selector" widget in the Geo-Dash. When Collecting, users can then open their geo-dash and see that widget's imagery set to the selected basemap. 
Closes COL-###
Log in as an admin and navigate to institution imagery. Create or update a Planet NICFI basemap layer and select a date. The list defaults to the most recent date. Save or update the widget, then navigate to that …
> COL-443: Imagery widget date

- src/js/project/PlotDesign.jsx
adds an alert when creating a project that has a custom shape.
Closes COL-350
Wizard
Admin
1. Create a new Institution Project. Procedd through the Wizard to the "Plot Design" Step. In the "Spatial Distribution" dropdown, select "SHP File"
Observe the helpful alert text which briefly appears.
---
> adds alert to plotdesign step

- src/clj/collect_earth_online/db/plots.clj
- src/css/custom.css
- src/js/collection.jsx
- src/js/survey/SurveyCollection.jsx
- src/js/utils/validation.js
- src/sql/changes/2023-04-17-lowercase-user-emails.sql
- src/sql/changes/2023-04-29-create-doi-table.sql
- src/sql/changes/2023-06-05-add-constraints.sql
- src/sql/changes/2023-11-20-add-confidence-comment-column.sql
- src/sql/functions/plots.sql
Add a confidence comment in case the confidence slider is present during collection phase.
Closes COL-
Collection > Confidence
User
1. As an admin, set the option for a confidence slider to true;
2. As a user, go to the collection page;
3. answer all the questions (with the exception of the confidence comment box) and click save;
4. An alert should pop up telling the user that they need to answer the comment;
5. answer the comment;
6. The user should be able to save the questions now. 
If there's a confidence slider set for the project, a text box should also be present so that the users can input their comment about the project. This comment is required.
ALERT:
WITH COMMENT:
> Add confidence_comment field and fix css

- src/js/geoDash.jsx
Adds a button to the Geo Dash that toggles the visibility of plot samples.
Closes COL-510
GeoDash
Admin
Navigate to an institution project and go to collection. From there, go to first plot and then to "Geo-Dash." Observe the "Show Plot Samples" button above. Toggle that button
Observe button text and style change along with visibility of plot samples
> Andy/col 510/geodash samples

- deps.edn
- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/ce_project.clj
- src/clj/collect_earth_online/generators/external_file.clj
Parse relevant files from `.cep` zips to enable importing surveys created in Collect.
Closes COL-553
1. Move a `.cep` file to the `/tmp` folder.
2. unzip the file using the function `collect-earth-online.generators.external-file/unzip-project` passing the file name
3. Call the function `collect-earth-online.generators.ce-project/create-project-survey` passing the file name.
4. The result must be the survey data structured in the way CEO is able to process. To grab some reference data to compare, the tester can retrieve some by selecting the column `survey_questions` from the `projects` table[
> COL-553: Import Collect's survey

- src/js/imagery/imageryOptions.js
- src/js/reviewInstitution.jsx
adds placeholder text to prompt the user to input band option, eg "Max (one or three bands, separated by commas)"
Closes COL-566
GeoDash
Admin
1. navigate to a test project's "configure geodash" page. edit or create a new widget. select "Sentinel 2" as the Image Source. observe the helpful placeholder value of "min" and "max" fields
mild pleasant surprise
---
> adds help text to band input

- src/clj/collect_earth_online/db/plots.clj
- src/sql/functions/plots.sql
fixes a bug in plots.sql related to plot_locks and fixes get-collection-plot so that assigned users are not routed to the first plot when done collecting the last one
Closes COL-549
- [ x No new reflection warnings (`clojure -M:check-reflection`)
Collection
User
1. Create a project. assign overlapping QAQC to at least one other user. log in as that user and collect required plots. 
upon collection of the final plot, a js/alert appears apprising user there are no more plots to collect
> Andy/col 549/assigned navigation

- deps.edn
- src/clj/collect_earth_online/db/projects.clj
- src/clj/collect_earth_online/generators/external_file.clj
- src/sql/changes/2023-12-12-change-extra-infos-column-types.sql
- src/sql/functions/plots.sql
- src/sql/functions/project.sql
Extra fields in CSV and SHP files for plots and samples were not being stored in order. This PR aims to fix it by changing the column types from jsonb to json and using ordered maps.
Closes COL-596
Project Wizard > Plot design
Collection > Plot information
Admin/User
1. Create a CSV using the example given by CEO
2. Add some extra columns to the CSV
3. Upload the CSV for plot design and finish project creation
4. Go to the collection page and check the `Plot Information`, the data here should be in the same order as it was in the CSV.
> COL-596: Enhancement/keep extra info in order

- src/js/components/svg/SvgIcon.jsx
- src/js/survey/AnswerDesigner.jsx
- src/js/survey/SurveyCard.jsx
- src/js/survey/SurveyDesignQuestion.jsx
- src/sql/functions/plots.sql
Recovering reorder of subquestions
Closes COL-###
Admin
1. Create a project and go to the survey questions page
2. Create a few questions and add child questions to some of them
3. Click on the up and down arrows in front of the subquestions 
4. The questions should be reordered
Only questions of the same level can be reordered. Once they are reordered, the survey preview should correctly display the order of the questions.
> Recover reorder sub questions

- src/js/collection.jsx
- src/js/survey/SurveyCollectionAnswers.jsx
Users had to keep selecting the same samples for every question. This PR fixes this issue by allowing no samples to be selected and only answering for the ones that are visible but have no answers.
Collection > survey answers
User
1. Create a project with several samples per plot and at least a few questions and subquestions
2. Go to the collection page
3. Select a couple of samples and try answering all the questions for them.
4. Repeat item 3 untill all samples have been answered
Users should be able to answer questions for the samples selected earlier. if no samples are selected for child questions, the answer will be set for every unanswered samples present in the map
> Improve sample selection in collection

- src/js/collection.jsx
- src/js/utils/mercator.js
adds a UI element to the collection page that toggles the visibility of the plot boundary or samples
Closes COL-639
Collection
Admin
Navigate to the collection page of an open project. observe the "show/hide plot/samples" buttons in the "External Tools." Enjoy a moment of serenity. Click the button.
1.
observe the plot boundary and samples toggle visibility
> includes frontend toggle for plot and samples in collection

- src/js/survey/SurveyCollection.jsx
Refactors code to prevent drawtool on projects where it is not allowed
Closes COL-595
Collection
Admin
1. Create a new project or navigate to one in which users are allowed to draw polygons. During Collection, attempt to draw a point on the map. Observe that this is impossible. 
---
> updates default drawtool

- src/py/gee/inputs.py
- src/py/gee/utils.py
The NDFI timeseries displayed in the degradation tool was showing wrong data. This PR fixes it by using TOA imagery instead of L2 imagery.
Closes COL-572
Geodash > Degradation tool
Admin/User
1. Create a project and configure the degradation tool in geodash widget creation
2. Navigate to the collection page
3. Open the geodash widget
4. Check that numbers in the degradation time series are not all tending to 1 and instead, are showing correct values.
> COL-572: Fix NDFI time series from degradation tool

- src/clj/collect_earth_online/db/projects.clj
- src/js/survey/SurveyCardList.jsx
Some projects, including those referenced in COL-577, are saved in our db so that each answer in its survey_questions jsonb data has a cardOrder value of 0. this munges the order of survey_question data on export and makes further rearranging of cards impossible on the frontend as well. As it is now, it is not possible to recapture the intended order of projects for which this is the case. This PR proposes a method by which users may still update the frontend order of survey question cards.
Closes COL-577
- [x ] No …
> validates projects from db and fixes broken cardOrders

- src/js/survey/NewQuestionDesigner.jsx
- src/js/survey/SurveyCardList.jsx
Currently, survey creation is awkward when users try to copy child questions to use as new parent questions, or when users try to copy existing questions to use as child questions. This PR allows for child question copying both ways.
Closes COL-588
Survey
Admin
1. Create a new project. navigate directly to "survey questions"
2. create two questions: "a parent question" and "a child question"
3. copy "a child question" as a child of "a parent question" …
> updates survey create and copy methods to smooth child copying

- src/py/gee/utils.py
Fixes imagery displayed in the degradation tool widget when a user clicks on a point in time in the time series graph
Closes COL-698
Geodash
2. Add a Degradation Tool widget in the geodash page
3. Start interpreting plots, go to geodash and click in a few points in the time series of the widget.
Widget should display the image correctly.
> Fix degradation tool imagery when selecting a point in time

- src/js/survey/SurveyCollection.jsx
The confidence slider was not reseting its position after answers were saved from one plot and the user navigated to another. This PR fixes this issue
Closes COL-700
Collection > Side Panel > Confidence slider
User
1. Create a project with confidence enabled
2. Navigate to the collection page
3. Answer the questions and set the confidence slider
4. Save answers for the plot and navigate to another one
The confidence slider should reset its value and the handle position
> COL-700: Reset confidence slider position for every question.

- src/clj/collect_earth_online/db/plots.clj
- src/js/utils/mercator.js
- src/sql/functions/plots.sql
This PR changes the application to allow users to click in a plot (if the cluster has only 1 plot) and go to its interpretation.
Closes COL-715
Collection > Plot Navigation
User
1. Create a project and go to the collection page
2. Click on a cluster of plots that is marked with '1'
3. Collect data for that plot
After clicking the cluster, the map should zoom in that area and open the survey collection for that specific plot.
> COL-715: Select plot from map

- src/js/survey/NewQuestionDesigner.jsx
- src/js/survey/SurveyCardList.jsx
Copying card level question to a child and vice-versa was broken in the last deployment. This PR intends to solve this issue
Admin
1. Start project creation
2. On the survey questions section, create a few questions
3. try copying a card level question to be a child question
4. Try copying a child question to be a card level question
Should copy the questions correctly
> Hotfix: Fix broken copy question

- src/css/custom.css
- src/js/collection.jsx
Sort Plot Info fields alphabetically, requested at FAO. Also changed formatting, I can revert if ugly.
Users
Add a plot file with props and check if sorted properly in collection view.
> Sort plot info alphabetically and add formatting

- src/sql/functions/plots.sql
Adds the visible_id fields for querying plot and sample tables for exporting shapefiles
Closes COL-###
Projects > Export shapefiles
Admin
2. Go to the project overview page and export the shapefiles
3. make sure the shapefiles contain the following properties `sample_id`, `plot_id` and `sample_int`.
`sample_id` and `plot_id` should correspond to the visible_ids present in the `samples` and `plots` tables respectively. `sample_int` is the internal id for the samples
> HOTFIX: Adding visible_ids for exporting shapefiles

- src/js/utils/validation.js
Removes validation with wrong calculations for assigning users with the QAQC overlap feature.
Closes COL-717
Wizard > Plot Design > QAQC
Admin
1. Start project creation and navigate to the `Plot Design` tab.
2. Create 10 plots by using the `random` spatial distribution. 
3. Assign 10 users and set QAQC to overlap 100% and 2 reviews (make sure you have access to at least one of the assigned user accounts).
4. Log in an assigned user, and start interpreting plots. Each user must have exactly 2 plots assigned to them.
Make sure the project can be created and that it assigns correctly the number of plots per user
> COL-717: Removing wrong validation from project creation

- src/clj/collect_earth_online/generators/external_file.clj
There were issues when creating plots and samples from csv/shp files. This PR aims to fix this issue
Closes COL-726
Closes COL-728
Closes COL-729
> COL-728: Enhancement/plot file messages

- src/clj/collect_earth_online/db/projects.clj
- src/js/survey/SurveyCollection.jsx
This PR Fixes the user assignment using the percentage of plots and the check for sum of answers, in which the validation would fail in case the answer was 0, due to 0 being falsy in javascript.
> HOTFIX: Fix percent user assignment and sum of answers check

- src/clj/collect_earth_online/db/users.clj
Fixes bug that impedes a user to request membership for an institution
Closes COL-718
Institutions > Users > Member
User
1. As a logged in <user_1>, access an institution in which you are not a member
2. Navigate to the users tab
3. click request membership
4. Log out with <user_1> and login with <user_2>, which is an admin for that institution
5. Approve membership of <user_1>
Requesting membership should work without errors.
> COL-718: Bugfix/request membership

- src/clj/collect_earth_online/proxy.clj
We weren't fetching any of the 2024 dates for planet nicfi. This was due to the request being limited to a few entries only. This PR sets the page_size to 150 entries.
Closes COL-###
Collection > Imagery
Admin/User
1. Enable planet NICFI imagery in a project
2. Navigate to the collection page as an user or admin
3. change the imagery to Planet NICFI
4. See that the dropdown now has 2024 dates listed
5. choose a date and check that the imagery is displayed
> Bugfix: 2024 planet dates

- deps.edn
- src/clj/collect_earth_online/handlers.clj
Sentry integration to CEO to make it easier tracking requests and errors
Closes COL-759
> COL-759: Adding sentry integration to ceo

- src/js/project/CreateProjectWizard.jsx
- src/js/project/Overview.jsx
- src/js/project/PlotDesign.jsx
- src/js/project/PlotStep.jsx
Add another type of project. By changing the dropdown value between Normal project and Simplified project the institution admin will be able to choose between the two types. A simplified project does not have user assignment, qaqc, sample design and survey rules
Closes COL-820
Wizard > create simplified project
Admin
1. Run the application
2. Go to the project wizard.
3. Change the project type
4. Check that the steps stated in the purpose section are no longer present
5. Create the project.
---
> COL-820: Simplified project creation

- src/js/widgetLayoutEditor.jsx
Adds default dates for geodash degradation tool
Closes COL-858
Admin
2. Go to the project overview page
3. Click configure geodash
4. Add a Degradation widget, check that start date is set to 2013-01-01 and end date is today's date
> default dates for degradation tool

- src/clj/collect_earth_online/db/users.clj
- src/clj/collect_earth_online/routing.clj
- src/js/register.jsx
Adds resend-validation-email functionality so that existing users (by email) can attempt to validate again.
Closes COL-928
- [x ] No new reflection warnings (`clojure -M:check-reflection`)
Login/Registration
User
1. click the "login" button in the top corner to navigate to the login page.
2. click the "register" button to ogin to registration
3. type in an email that does not correspond to a real or existing user.
4. observe the registration page as normal.
5. replace the email with that of an existing user.
6. click …
> Andy/col 928/resend reset email

- src/js/register.jsx
Removes second checkbox from registration page
Closes COL-957
Registration
Visitor
1. navigate to app and click the "login" button in the upper right corner. From the Login page, click the "Register" button in the bottom-right corner.
2. enter an email address of a user that does not exist in the database. press TAB or click away from the text box.
3. observe the password fields, and below them but one checkbox related to the terms of service.
4. enter …
> removes element and conditions from ui

- src/clj/collect_earth_online/db/geodash.clj
Adds check-initialized function call to make sure the ee library was initialized
Closes COL-###
> Add check-initialized on the validate visparams func

- src/js/collection.jsx
- src/js/project/CreateProjectWizard.jsx
- src/js/project/PlotDesign.jsx
- src/js/project/ReviewForm.jsx
- src/sql/changes/2025-06-23-shared-imagery-table.sql
- src/sql/functions/imagery.sql
This PR creates a new table for shared imagery that are public for everyone on the platform and changes the meaning of `visibility` to allow either the imagery to be accessed by everyone or only by institution members.
Closes COL-969
1.
---
> Changing permissions for imagery

- src/clj/collect_earth_online/api.clj
- src/clj/collect_earth_online/db/projects.clj
- src/js/collection.jsx
- src/sql/functions/project.sql
Adds a SQL function that returns a users institution role id based on a given project id. This is used in the server route that gets a project by id on user navigation. When a user with access privileges (eg, an admin or institution_user) attempts to collect a sample on that project, the frontend will now conditionally render an alert modal or complete the navigation to collection based on the role id included as part of the project in question.
Closes COL-958
- [ x] No new reflection warnings (`clojure …
> Andy/col 958/admin review verification

- src/css/custom.css
- src/css/sidebar.css
- src/js/collection.jsx
- src/js/components/CollectionSidebar.jsx
- src/js/components/SurveyQuestions.jsx
- src/js/home.jsx
- src/js/utils/constants.jsx
Sprinkles some CSS zhuzh and unhides the mapControls from underneath the collection sidebar.
also restores 'go to plot' functionality in collection mode.
Closes COL-###
1.
---
> Andy/col bug/28082025

- src/clj/collect_earth_online/db/geoai.clj
- src/clj/collect_earth_online/db/geodash.clj
- src/js/components/CollectionSidebar.jsx
- src/js/geodash/DynamicWorldDesigner.jsx
- src/js/geodash/MapWidget.jsx
- src/js/geodash/constants.js
- src/js/project/PlotDesign.jsx
- src/js/widgetLayoutEditor.jsx
- src/py/gee/routes.py
- src/py/gee/utils.py
Adds "Dynamic World" as a widget type in the geo-dash.
Closes COL-1021
Collection
GeoDash
User
1. From the app homepage, click the arrow on the left side of the screen to open the slider pane. select your institution from the list and click to navigate to the institution page.
2. from the institution page, choose a project and click the yellow edit button.
3. from the project page, click "configure geo-dash"
4. from geodash configuration, click "add widget" and select "dynamic world" from the list
5. Choose a start and end date, then click "create"
6. navigate back to the project page. it may be in a different browser tab.
7. click "collect"
8. from the project collection page, click the next arrow to begin collection. click "go to geo-dash."
9. identify the widget created in step 5 and …
> Andy/col 1021/dynamic degradation widget
